-- AI Radar Database Seed Script
-- Run this in Supabase Dashboard > SQL Editor
-- Inserts 22 well-known AI products

INSERT INTO products (slug, name, name_en, name_zh, description, description_en, description_zh, website_url, github_url, logo_url, category, subcategory, tags, tech_stack, pricing_model, pricing_url, availability_status, commercialization_status, funding_stage, founder_info, launch_date, confidence_score, confidence_level, validation_signals, source_count, weekly_growth_rate, monthly_growth_rate, github_stars)
VALUES
('chatgpt', 'ChatGPT', 'ChatGPT', 'ChatGPT', 'Conversational AI assistant by OpenAI, capable of natural language understanding and generation.', 'Conversational AI assistant by OpenAI.', 'OpenAI 开发的对话式 AI 助手。', 'https://chat.openai.com', NULL, 'https://cdn.openai.com/chatgpt/favicon.ico', 'AI Assistant', 'Chatbot', '{"llm","chatbot","generative-ai","openai"}', '{"gpt-4","gpt-3.5"}', 'freemium', 'https://openai.com/pricing', 'active', 'Commercial - Subscription', 'Series C', 'Sam Altman, Greg Brockman, Ilya Sutskever', '2022-11-30', 100, 'high', '{"wikipedia":true,"major_news":true,"product_hunt":true}', 15, 2.5, 8.3, NULL),
('claude', 'Claude', 'Claude', 'Claude', 'AI assistant by Anthropic focused on helpful, harmless, and honest interactions.', 'AI assistant by Anthropic.', 'Anthropic 开发的 AI 助手。', 'https://claude.ai', NULL, 'https://claude.ai/favicon.ico', 'AI Assistant', 'Chatbot', '{"llm","chatbot","anthropic","constitutional-ai"}', '{"claude-3","claude-3.5"}', 'freemium', 'https://www.anthropic.com/pricing', 'active', 'Commercial - Subscription', 'Series D', 'Dario Amodei, Daniela Amodei', '2023-03-14', 100, 'high', '{"wikipedia":true,"major_news":true,"product_hunt":true}', 12, 3.1, 10.2, NULL),
('midjourney', 'Midjourney', 'Midjourney', 'Midjourney', 'AI image generation tool that creates art from text prompts.', 'AI image generation from text prompts.', '从文本提示生成图像的 AI 工具。', 'https://www.midjourney.com', NULL, 'https://www.midjourney.com/favicon.ico', 'Image Generation', 'Text-to-Image', '{"image-generation","generative-ai","art","diffusion"}', '{"diffusion-model"}', 'paid', 'https://www.midjourney.com/pricing', 'active', 'Commercial - Subscription', 'Series A', 'David Holz', '2022-07-12', 100, 'high', '{"wikipedia":true,"major_news":true,"product_hunt":true}', 10, 1.8, 5.6, NULL),
('gemini', 'Google Gemini', 'Google Gemini', 'Google Gemini', 'Multimodal AI model by Google, successor to Bard.', 'Google''s multimodal AI model.', 'Google 的多模态 AI 模型。', 'https://gemini.google.com', NULL, 'https://gemini.google.com/favicon.ico', 'AI Assistant', 'Chatbot', '{"llm","google","multimodal","generative-ai"}', '{"gemini-pro","gemini-ultra"}', 'freemium', 'https://ai.google.dev/pricing', 'active', 'Commercial - API & Subscription', 'Public Company', 'Google DeepMind', '2023-12-06', 100, 'high', '{"wikipedia":true,"major_news":true}', 14, 2.0, 7.1, NULL),
('llama', 'Llama', 'Llama', 'Llama', 'Open-source large language model by Meta AI.', 'Open-source LLM by Meta.', 'Meta 开源的大语言模型。', 'https://llama.meta.com', 'https://github.com/meta-llama/llama', 'https://llama.meta.com/favicon.ico', 'LLM', 'Open Source Model', '{"llm","open-source","meta","transformer"}', '{"llama-3","llama-3.1","llama-3.2"}', 'open_source', NULL, 'active', 'Open Source - Commercial License', 'Public Company', 'Meta AI', '2023-02-24', 100, 'high', '{"wikipedia":true,"major_news":true,"github":true}', 18, 4.2, 15.0, 52000),
('cursor', 'Cursor', 'Cursor', 'Cursor', 'AI-powered code editor built on VS Code with integrated AI coding assistant.', 'AI-first code editor.', '基于 VS Code 的 AI 代码编辑器。', 'https://www.cursor.com', NULL, 'https://www.cursor.com/favicon.ico', 'Developer Tools', 'AI IDE', '{"coding","developer-tools","ide","ai-assistant"}', '{"vscode","gpt-4","claude"}', 'freemium', 'https://www.cursor.com/pricing', 'active', 'Commercial - Subscription', 'Series B', 'Anysphere', '2023-01-15', 95, 'high', '{"product_hunt":true,"hackernews":true,"github":true}', 8, 5.1, 20.3, NULL),
('notion-ai', 'Notion AI', 'Notion AI', 'Notion AI', 'AI-powered writing and productivity features integrated into Notion workspace.', 'AI features in Notion workspace.', 'Notion 工作区中的 AI 功能。', 'https://www.notion.so/product/ai', NULL, 'https://www.notion.so/favicon.ico', 'Productivity', 'AI Writing', '{"productivity","writing","workspace","ai-assistant"}', '{"gpt-4"}', 'paid', 'https://www.notion.so/pricing', 'active', 'Commercial - Add-on', 'Series C', 'Ivan Zhao', '2023-02-22', 95, 'high', '{"wikipedia":true,"major_news":true}', 7, 1.2, 4.5, NULL),
('copilot', 'GitHub Copilot', 'GitHub Copilot', 'GitHub Copilot', 'AI pair programmer that suggests code completions in real-time.', 'AI pair programmer by GitHub and OpenAI.', 'GitHub 和 OpenAI 合作的 AI 编程助手。', 'https://github.com/features/copilot', NULL, 'https://github.com/favicon.ico', 'Developer Tools', 'Code Completion', '{"coding","github","openai","code-completion"}', '{"gpt-4","codex"}', 'paid', 'https://github.com/pricing', 'active', 'Commercial - Subscription', 'Acquired (Microsoft)', 'GitHub / Microsoft', '2021-06-29', 100, 'high', '{"wikipedia":true,"major_news":true,"github":true}', 20, 2.8, 9.1, NULL),
('stable-diffusion', 'Stable Diffusion', 'Stable Diffusion', 'Stable Diffusion', 'Open-source text-to-image diffusion model by Stability AI.', 'Open-source text-to-image model.', 'Stability AI 的开源文本到图像模型。', 'https://stability.ai', 'https://github.com/Stability-AI/stablediffusion', 'https://stability.ai/favicon.ico', 'Image Generation', 'Text-to-Image', '{"image-generation","open-source","diffusion","stability-ai"}', '{"diffusion-model","latent-diffusion"}', 'open_source', NULL, 'active', 'Open Source - Commercial API Available', 'Series B', 'Emad Mostaque', '2022-08-22', 100, 'high', '{"wikipedia":true,"major_news":true,"github":true}', 16, 1.5, 4.8, 62000),
('perplexity-ai', 'Perplexity AI', 'Perplexity AI', 'Perplexity AI', 'AI-powered search engine that provides cited answers from the web.', 'AI search engine with cited answers.', '提供引用答案的 AI 搜索引擎。', 'https://www.perplexity.ai', NULL, 'https://www.perplexity.ai/favicon.ico', 'Search', 'AI Search', '{"search","llm","research","qa"}', '{"llama-3","gpt-4","claude"}', 'freemium', 'https://www.perplexity.ai/pricing', 'active', 'Commercial - Subscription', 'Series B', 'Aravind Srinivas, Denis Yarats, Johnny Ho, Andy Konwinski', '2022-08-01', 95, 'high', '{"major_news":true,"product_hunt":true}', 9, 4.5, 18.2, NULL),
('kimi', 'Kimi', 'Kimi', 'Kimi 智能助手', 'Chinese AI assistant by Moonshot AI with long context window support.', 'Chinese AI assistant by Moonshot AI.', '月之暗面开发的中国 AI 助手，支持超长上下文。', 'https://kimi.moonshot.cn', NULL, 'https://kimi.moonshot.cn/favicon.ico', 'AI Assistant', 'Chatbot', '{"llm","chinese","moonshot","long-context"}', '{"moonshot-v1"}', 'freemium', NULL, 'active', 'Commercial - Free Beta', 'Series B', 'Yu Xin (月之暗面)', '2023-10-01', 90, 'high', '{"major_news":true}', 6, 3.2, 12.5, NULL),
('doubao', 'Doubao', 'Doubao', '豆包', 'AI assistant by ByteDance, integrated with Chinese ecosystem.', 'AI assistant by ByteDance.', '字节跳动开发的 AI 助手。', 'https://www.doubao.com', NULL, 'https://www.doubao.com/favicon.ico', 'AI Assistant', 'Chatbot', '{"llm","chinese","bytedance","multimodal"}', '{"doubao-pro"}', 'freemium', NULL, 'active', 'Commercial - Free Beta', 'Private (ByteDance)', 'ByteDance', '2023-05-01', 90, 'high', '{"major_news":true}', 7, 2.8, 11.0, NULL),
('deepseek', 'DeepSeek', 'DeepSeek', 'DeepSeek', 'Chinese open-source AI company known for coding models and cost-efficient training.', 'Chinese AI company with open-source coding models.', '中国开源 AI 公司，以编程模型和低成本训练闻名。', 'https://www.deepseek.com', 'https://github.com/deepseek-ai', 'https://www.deepseek.com/favicon.ico', 'LLM', 'Open Source Model', '{"llm","open-source","chinese","coding","deepseek"}', '{"deepseek-v3","deepseek-coder"}', 'open_source', NULL, 'active', 'Open Source - API Available', 'Series B', 'DeepSeek AI', '2023-06-15', 95, 'high', '{"github":true,"major_news":true,"hackernews":true}', 11, 6.2, 25.0, 28000),
('qwen', 'Qwen', 'Qwen', '通义千问', 'Large language model family by Alibaba Cloud, available in multiple sizes.', 'LLM family by Alibaba Cloud.', '阿里巴巴云开发的大语言模型系列。', 'https://qwen.ai', 'https://github.com/QwenLM', 'https://qwen.ai/favicon.ico', 'LLM', 'Open Source Model', '{"llm","open-source","alibaba","chinese"}', '{"qwen-2.5","qwen-max"}', 'open_source', NULL, 'active', 'Open Source - Commercial License', 'Public Company (Alibaba)', 'Alibaba Cloud', '2023-08-01', 95, 'high', '{"github":true,"major_news":true}', 13, 4.8, 19.5, 35000),
('grok', 'Grok', 'Grok', 'Grok', 'AI chatbot by xAI (Elon Musk), integrated with X (Twitter) platform.', 'AI chatbot by xAI, integrated with X.', 'xAI 开发的 AI 聊天机器人，与 X 平台集成。', 'https://grok.x.ai', NULL, 'https://x.ai/favicon.ico', 'AI Assistant', 'Chatbot', '{"llm","xai","elon-musk","twitter"}', '{"grok-2","grok-3"}', 'paid', 'https://x.com/premium', 'active', 'Commercial - X Premium Subscription', 'Private (xAI)', 'Elon Musk', '2023-11-04', 90, 'high', '{"major_news":true,"product_hunt":true}', 8, 2.1, 7.8, NULL),
('comfyui', 'ComfyUI', 'ComfyUI', 'ComfyUI', 'Node-based GUI for Stable Diffusion and other diffusion models.', 'Node-based GUI for diffusion models.', '基于节点的扩散模型 GUI。', 'https://github.com/comfyanonymous/ComfyUI', 'https://github.com/comfyanonymous/ComfyUI', 'https://github.com/favicon.ico', 'Image Generation', 'Tool', '{"image-generation","open-source","ui","stable-diffusion"}', '{"python","pytorch"}', 'open_source', NULL, 'active', 'Open Source', 'Community', 'comfyanonymous', '2023-01-20', 85, 'high', '{"github":true,"hackernews":true}', 5, 3.8, 14.2, 45000),
('ollama', 'Ollama', 'Ollama', 'Ollama', 'Run large language models locally with a simple CLI interface.', 'Run LLMs locally with a simple CLI.', '用简单的 CLI 在本地运行大语言模型。', 'https://ollama.com', 'https://github.com/ollama/ollama', 'https://ollama.com/favicon.ico', 'Developer Tools', 'Model Runner', '{"llm","open-source","local","developer-tools"}', '{"go","llama.cpp"}', 'open_source', NULL, 'active', 'Open Source', 'Community', 'Jeffrey Morgan', '2023-06-10', 90, 'high', '{"github":true,"hackernews":true,"product_hunt":true}', 12, 5.5, 22.0, 98000),
('runway', 'Runway', 'Runway', 'Runway', 'AI video and image generation platform, creators of Gen-2 and Gen-3 models.', 'AI video and image generation platform.', 'AI 视频和图像生成平台。', 'https://runwayml.com', NULL, 'https://runwayml.com/favicon.ico', 'Video Generation', 'Text-to-Video', '{"video-generation","image-generation","generative-ai","runway"}', '{"gen-3","gen-2"}', 'freemium', 'https://runwayml.com/pricing', 'active', 'Commercial - Subscription', 'Series D', 'Cristobal Valenzuela, Anastasis Germanidis', '2021-03-01', 90, 'high', '{"major_news":true,"product_hunt":true}', 6, 2.3, 8.5, NULL),
('sora', 'Sora', 'Sora', 'Sora', 'Text-to-video AI model by OpenAI capable of generating realistic video clips.', 'Text-to-video AI model by OpenAI.', 'OpenAI 的文本到视频 AI 模型。', 'https://openai.com/sora', NULL, 'https://cdn.openai.com/favicon.ico', 'Video Generation', 'Text-to-Video', '{"video-generation","openai","generative-ai","multimodal"}', '{"diffusion-transformer"}', 'paid', NULL, 'active', 'Commercial - ChatGPT Plus/Pro', 'Series C', 'OpenAI', '2024-02-15', 95, 'high', '{"major_news":true}', 10, 3.0, 12.0, NULL),
('kling-ai', 'Kling AI', 'Kling AI', '可灵', 'AI video generation model by Kuaishou, competitor to Sora.', 'AI video generation by Kuaishou.', '快手开发的 AI 视频生成模型，Sora 的竞争者。', 'https://klingai.com', NULL, 'https://klingai.com/favicon.ico', 'Video Generation', 'Text-to-Video', '{"video-generation","chinese","kuaishou","generative-ai"}', '{"kling-v1"}', 'freemium', NULL, 'active', 'Commercial - Free Beta', 'Public Company (Kuaishou)', 'Kuaishou', '2024-06-01', 85, 'high', '{"major_news":true}', 5, 4.0, 16.0, NULL),
('n8n', 'n8n', 'n8n', 'n8n', 'Workflow automation platform with AI agent integration capabilities.', 'Workflow automation with AI agents.', '带有 AI 代理集成的工作流自动化平台。', 'https://n8n.io', 'https://github.com/n8n-io/n8n', 'https://n8n.io/favicon.ico', 'Automation', 'Workflow', '{"automation","workflow","ai-agents","open-source"}', '{"typescript","vue"}', 'freemium', 'https://n8n.io/pricing', 'active', 'Commercial - Self-hosted & Cloud', 'Series B', 'Jan Oberhauser', '2019-05-01', 85, 'high', '{"github":true,"hackernews":true}', 7, 3.5, 13.0, 50000),
('dify', 'Dify', 'Dify', 'Dify', 'Open-source LLM app development platform with visual workflow builder.', 'Open-source LLM app development platform.', '开源 LLM 应用开发平台。', 'https://dify.ai', 'https://github.com/langgenius/dify', 'https://dify.ai/favicon.ico', 'Developer Tools', 'LLM Platform', '{"llm","open-source","platform","chinese"}', '{"python","next.js","typescript"}', 'open_source', NULL, 'active', 'Open Source - Cloud Available', 'Series A', 'Dify Team', '2023-05-15', 85, 'high', '{"github":true,"product_hunt":true}', 6, 5.0, 20.0, 55000)
ON CONFLICT (slug) DO NOTHING;

-- Verify
SELECT COUNT(*) AS total_products FROM products;
