-- =====================================================================
-- AI Radar Phase E — Launch Events Seed (120 events)
-- File: supabase/seed-phase-e-launch-events-120.sql
-- Author: 寇豆码 (Engineer)
-- Date: 2026-05-31
-- Related: T03 (A线-W1)
--
-- 范围:
--   - 120 条 launch_events，覆盖 6 个数据源
--   - 时间范围: 2025-12-01 ~ 2026-05-29
--   - event_type 分布: launch(70) / major_update(30) / open_source(10) / funding(5) / milestone(5)
--   - 每条至少关联 1 个 product (由 name → slug 匹配)
--
-- 数据源分布 (5+ sources):
--   producthunt: 30
--   hackernews: 25
--   github:     25
--   x:          20
--   arxiv:      15
--   xiaohongshu: 5 (额外)
--   Total:      120
--
-- 幂等策略:
--   INSERT ... ON CONFLICT (source, source_id) DO UPDATE
-- =====================================================================

INSERT INTO launch_events (
  product_id, source, source_url, source_id, event_type,
  title, body, author, engagement,
  detected_at, event_at, confidence, raw_data
)
SELECT
  p.id AS product_id,
  e.source, e.source_url, e.source_id, e.event_type,
  e.title, e.body, e.author, e.engagement::jsonb,
  e.detected_at::timestamptz, e.event_at::timestamptz, e.confidence, e.raw_data::jsonb
FROM (VALUES
  -- ===== producthunt (30) =====
  ('cursor',          'producthunt', 'https://www.producthunt.com/posts/cursor-0-50',       'ph-cursor-0-50',          'major_update',
   'Cursor 0.50 — Multi-Agent Coding', 'Released agent mode that orchestrates Plan → Code → Test agents in parallel.',
   'cursor_team',  '{"upvotes":4820,"comments":312}', '2026-04-22', '2026-04-22', 0.95,
   '{"tagline":"Ship faster with parallel coding agents","rank":1}'),
  ('replit',          'producthunt', 'https://www.producthunt.com/posts/replit-agent-v3',   'ph-replit-agent-v3',      'launch',
   'Replit Agent v3 — Full-stack from Voice', 'Voice-to-deploy: describe your app, get a deployed URL in minutes.',
   'replit_team',  '{"upvotes":3210,"comments":198}', '2026-03-12', '2026-03-12', 0.92,
   '{"tagline":"Voice in, deployed app out","rank":2}'),
  ('claude',          'producthunt', 'https://www.producthunt.com/posts/claude-4-7',         'ph-claude-4-7',           'major_update',
   'Claude 4.7 Sonnet — 1M Context General Availability', 'Anthropic releases 1M context to GA, with new Files API.',
   'anthropic_team', '{"upvotes":5680,"comments":421}', '2026-05-08', '2026-05-08', 0.97,
   '{"tagline":"Long context for everyone","rank":1}'),
  ('manus',           'producthunt', 'https://www.producthunt.com/posts/manus-1-5',         'ph-manus-1-5',            'major_update',
   'Manus 1.5 — Multi-modal General Agent', 'Adds screenshot understanding and 50+ tool integrations.',
   'manus_team',   '{"upvotes":2840,"comments":165}', '2026-04-30', '2026-04-30', 0.93,
   '{"tagline":"See, click, automate","rank":3}'),
  ('lindy',           'producthunt', 'https://www.producthunt.com/posts/lindy-2',            'ph-lindy-2',              'launch',
   'Lindy 2.0 — Build AI Employees in Minutes', 'Drag-and-drop agent builder with CRM integrations.',
   'lindy_team',   '{"upvotes":1820,"comments":98}',  '2026-02-18', '2026-02-18', 0.86,
   '{"tagline":"Your AI employee builder","rank":5}'),
  ('synthesia',       'producthunt', 'https://www.producthunt.com/posts/synthesia-3',        'ph-synthesia-3',          'major_update',
   'Synthesia 3.0 — Real-time Avatar Engine', 'Avatars now respond in <500ms with custom voice cloning.',
   'synthesia_team','{"upvotes":2210,"comments":142}','2026-01-29', '2026-01-29', 0.90,
   '{"tagline":"Real-time AI avatars","rank":4}'),
  ('heygen',          'producthunt', 'https://www.producthunt.com/posts/heygen-3',           'ph-heygen-3',             'launch',
   'HeyGen 3.0 — Video Translation Studio', 'Translate videos into 175 languages while preserving voice and lip sync.',
   'heygen_team',  '{"upvotes":2640,"comments":178}','2026-03-25', '2026-03-25', 0.91,
   '{"tagline":"Speak any language","rank":3}'),
  ('intercom-fin',    'producthunt', 'https://www.producthunt.com/posts/intercom-fin-2',     'ph-intercom-fin-2',       'major_update',
   'Intercom Fin 2.0 — Voice + Email Channels', 'Fin now handles inbound calls and complex email threads.',
   'intercom_team','{"upvotes":3110,"comments":221}','2026-04-09', '2026-04-09', 0.93,
   '{"tagline":"AI agent for every channel","rank":2}'),
  ('khanmigo',        'producthunt', 'https://www.producthunt.com/posts/khanmigo-math',     'ph-khanmigo-math',        'launch',
   'Khanmigo for Math Teachers', 'AI co-pilot for math teachers to draft lesson plans and grade work.',
   'khan_team',    '{"upvotes":1450,"comments":87}', '2026-02-04', '2026-02-04', 0.85,
   '{"tagline":"Your math teaching assistant","rank":6}'),
  ('jasper-ai',       'producthunt', 'https://www.producthunt.com/posts/jasper-brand-voice-2','ph-jasper-brand-v2',      'major_update',
   'Jasper Brand Voice 2.0', 'Train Jasper on your brand in 5 minutes, get on-voice output instantly.',
   'jasper_team',  '{"upvotes":1280,"comments":64}', '2026-01-15', '2026-01-15', 0.84,
   '{"tagline":"On-brand at AI speed","rank":7}'),
  ('ada-support',     'producthunt', 'https://www.producthunt.com/posts/ada-actions',        'ph-ada-actions',          'launch',
   'Ada Actions — Outcome-based Automation', 'Pay only for resolved tickets. Ada handles the rest.',
   'ada_team',     '{"upvotes":940,"comments":52}',  '2026-03-04', '2026-03-04', 0.82,
   '{"tagline":"Pay per resolution","rank":8}'),
  ('speak-app',       'producthunt', 'https://www.producthunt.com/posts/speak-v3',           'ph-speak-v3',             'major_update',
   'Speak v3 — Pronunciation Coach', 'Phoneme-level feedback with 96% accuracy in independent benchmarks.',
   'speak_team',   '{"upvotes":1620,"comments":108}','2026-04-02', '2026-04-02', 0.88,
   '{"tagline":"Sound like a native","rank":4}'),
  ('mem-ai',          'producthunt', 'https://www.producthunt.com/posts/mem-2',              'ph-mem-2',                'launch',
   'Mem 2.0 — Self-organizing Workspace', 'AI automatically builds a knowledge graph from your notes.',
   'mem_team',     '{"upvotes":1120,"comments":71}', '2026-02-26', '2026-02-26', 0.83,
   '{"tagline":"Notes that organize themselves","rank":7}'),
  ('playht',          'producthunt', 'https://www.producthunt.com/posts/playht-3',           'ph-playht-3',             'major_update',
   'PlayHT 3.0 — Ultra-low Latency Voice API', 'Streaming TTS in <150ms with new multilingual voices.',
   'playht_team',  '{"upvotes":880,"comments":49}',  '2026-05-15', '2026-05-15', 0.85,
   '{"tagline":"Real-time voice for every app","rank":9}'),
  ('replicate',       'producthunt', 'https://www.producthunt.com/posts/replicate-cog-2',    'ph-replicate-cog-2',      'launch',
   'Cog 2.0 — Python-based Model Packaging', 'Package any model with a single Python decorator.',
   'replicate_team','{"upvotes":760,"comments":42}','2026-01-22', '2026-01-22', 0.80,
   '{"tagline":"One decorator, one model","rank":10}'),
  ('komo',            'producthunt', 'https://www.producthunt.com/posts/komo-search',        'ph-komo-search',          'launch',
   'Komo Search — Ad-free Generative Answers', 'A clean, fast search engine powered by LLMs.',
   'komo_team',    '{"upvotes":520,"comments":38}',  '2026-03-18', '2026-03-18', 0.76,
   '{"tagline":"Search, not ads","rank":12}'),
  ('quizlet-qchat',   'producthunt', 'https://www.producthunt.com/posts/quizlet-qchat-2',    'ph-quizlet-qchat-2',      'major_update',
   'Q-Chat 2.0 — Multimodal Study Buddy', 'Snap a photo of your textbook, get a study set.',
   'quizlet_team', '{"upvotes":1010,"comments":67}', '2026-04-16', '2026-04-16', 0.84,
   '{"tagline":"Study smarter, not harder","rank":8}'),
  ('huggingface',     'producthunt', 'https://www.producthunt.com/posts/hf-spaces-2',        'ph-hf-spaces-2',          'major_update',
   'Hugging Face Spaces 2.0', 'Persistent GPU Spaces with one-click deploy from any model.',
   'hf_team',      '{"upvotes":1980,"comments":135}','2026-02-11', '2026-02-11', 0.89,
   '{"tagline":"GPU Spaces for everyone","rank":4}'),
  ('brave-search',    'producthunt', 'https://www.producthunt.com/posts/brave-summarizer',   'ph-brave-summarizer',     'launch',
   'Brave Summarizer — In-line AI Answers', 'Privacy-preserving summarization right in the SERP.',
   'brave_team',   '{"upvotes":1340,"comments":88}', '2026-05-21', '2026-05-21', 0.87,
   '{"tagline":"Private AI summaries","rank":5}'),
  ('claude',          'producthunt', 'https://www.producthunt.com/posts/claude-computer-use','ph-claude-computer-use',  'major_update',
   'Claude Computer Use General Availability', 'Claude can now control any GUI on any OS.',
   'anthropic_team','{"upvotes":6240,"comments":498}','2026-01-23', '2026-01-23', 0.98,
   '{"tagline":"AI that uses your computer","rank":1}'),
  ('groq',            'producthunt', 'https://www.producthunt.com/posts/groq-lpu-2',          'ph-groq-lpu-2',           'major_update',
   'Groq LPU v2 — 1200 tokens/sec inference', 'Custom silicon delivers 3x the previous generation.',
   'groq_team',    '{"upvotes":1640,"comments":112}','2026-03-31', '2026-03-31', 0.90,
   '{"tagline":"The fastest inference, again","rank":3}'),
  ('gemini',          'producthunt', 'https://www.producthunt.com/posts/gemini-3',            'ph-gemini-3',             'major_update',
   'Gemini 3.0 — Native Multimodal Reasoning', 'Tightly integrated vision + audio + text reasoning.',
   'google_team',  '{"upvotes":4120,"comments":287}','2026-04-25', '2026-04-25', 0.96,
   '{"tagline":"See, hear, reason","rank":1}'),
  ('cody',            'producthunt', 'https://www.producthunt.com/posts/sourcegraph-cody-2', 'ph-cody-2',               'launch',
   'Sourcegraph Cody 2.0 — Code-graph AI', 'Deep understanding of monorepos and call graphs.',
   'sourcegraph_team','{"upvotes":720,"comments":41}','2026-02-09', '2026-02-09', 0.79,
   '{"tagline":"AI that knows your codebase","rank":11}'),
  ('andiv-search',    'producthunt', 'https://www.producthunt.com/posts/andi-v2',            'ph-andi-v2',              'major_update',
   'Andi v2 — Conversational Search', 'Multi-turn search with image and video sources.',
   'andi_team',    '{"upvotes":430,"comments":28}',  '2026-05-02', '2026-05-02', 0.74,
   '{"tagline":"Search that talks back","rank":14}'),
  ('tabnine',         'producthunt', 'https://www.producthunt.com/posts/tabnine-enterprise','ph-tabnine-ent',         'launch',
   'Tabnine Enterprise — Private Model Hosting', 'Run Tabnine on your own VPC with full code privacy.',
   'tabnine_team', '{"upvotes":610,"comments":34}',  '2026-04-15', '2026-04-15', 0.81,
   '{"tagline":"AI code that stays private","rank":12}'),
  ('aiva',            'producthunt', 'https://www.producthunt.com/posts/aiva-mobile',        'ph-aiva-mobile',          'launch',
   'AIVA Mobile — AI Music on the Go', 'Compose, edit, and export music from your phone.',
   'aiva_team',    '{"upvotes":370,"comments":22}',  '2026-01-08', '2026-01-08', 0.71,
   '{"tagline":"Compose anywhere","rank":15}'),
  ('playground-ai',   'producthunt', 'https://www.producthunt.com/posts/playground-v3',      'ph-playground-v3',        'major_update',
   'Playground v3 — Real-time Canvas', 'Generate, edit, and remix images with friends live.',
   'playground_team','{"upvotes":850,"comments":58}','2026-03-26', '2026-03-26', 0.83,
   '{"tagline":"Create together, in real time","rank":9}'),
  ('claude',          'producthunt', 'https://www.producthunt.com/posts/claude-for-design','ph-claude-design',        'launch',
   'Claude for Design — Figma Plugin', 'Generate, refactor, and audit Figma designs in Claude.',
   'anthropic_team','{"upvotes":1820,"comments":108}','2026-02-27', '2026-02-27', 0.88,
   '{"tagline":"Claude meets Figma","rank":6}'),
  ('huggingface',     'producthunt', 'https://www.producthunt.com/posts/hf-leaderboard-v3','ph-hf-leaderboard-v3',    'major_update',
   'HF Open LLM Leaderboard v3', 'New benchmarks: GPQA, MATH-500, IFEval, BBH.',
   'hf_team',      '{"upvotes":1240,"comments":76}', '2026-04-04', '2026-04-04', 0.86,
   '{"tagline":"Harder benchmarks, real progress","rank":7}'),
  ('mutiny',          'producthunt', 'https://www.producthunt.com/posts/mutiny-ai-copy',     'ph-mutiny-ai-copy',       'launch',
   'Mutiny AI Copy — Auto-generate Landing Pages', 'Personalize copy and design by visitor intent.',
   'mutiny_team',  '{"upvotes":540,"comments":32}',  '2026-05-12', '2026-05-12', 0.78,
   '{"tagline":"Landing pages that personalize themselves","rank":13}'),

  -- ===== hackernews (25) =====
  ('deepseek',        'hackernews',  'https://news.ycombinator.com/item?id=deepseek-v4',     'hn-deepseek-v4',          'launch',
   'DeepSeek-V4 — 1T MoE with open weights', 'Chinese lab releases 1T MoE, beats Llama-4 on benchmarks.',
   'deepseek_team','{"upvotes":3240,"comments":612}','2026-01-19', '2026-01-19', 0.95,
   '{"hn_rank":1,"comments_top":"open weights, closed data"}'),
  ('huggingface',     'hackernews',  'https://news.ycombinator.com/item?id=hf-transformers-v5','hn-hf-transformers-v5', 'major_update',
   'Transformers v5 — Native MoE Support', 'First-class MoE, quantization, and TPU training.',
   'pcuenque',     '{"upvotes":1840,"comments":289}','2026-02-22', '2026-02-22', 0.91,
   '{"hn_rank":2,"comments_top":"MoE in 3 lines"}'),
  ('replicate',       'hackernews',  'https://news.ycombinator.com/item?id=replicate-stream','hn-replicate-stream',     'launch',
   'Replicate Streaming API — Real-time Model Output', 'Stream tokens, frames, and audio.',
   'bfirsh',       '{"upvotes":1120,"comments":178}','2026-03-09', '2026-03-09', 0.86,
   '{"hn_rank":4,"comments_top":"finally, real-time"}'),
  ('ollama',          'hackernews',  'https://news.ycombinator.com/item?id=ollama-vision',   'hn-ollama-vision',        'major_update',
   'Ollama Adds Native Vision Models', 'Run LLaVA, Qwen-VL, and Llama-4-Vision locally.',
   'jmorgan',      '{"upvotes":2360,"comments":421}','2026-04-11', '2026-04-11', 0.94,
   '{"hn_rank":1,"comments_top":"local vision, finally"}'),
  ('langchain',       'hackernews',  'https://news.ycombinator.com/item?id=langgraph-v2',   'hn-langgraph-v2',         'launch',
   'LangGraph v2 — Stateful Multi-agent Orchestration', 'Production-grade agent runtime with replay and observability.',
   'hwchase17',    '{"upvotes":1480,"comments":234}','2026-01-26', '2026-01-26', 0.88,
   '{"hn_rank":3,"comments_top":"this is the runtime we needed"}'),
  ('vllm',            'hackernews',  'https://news.ycombinator.com/item?id=vllm-v1',         'hn-vllm-v1',              'major_update',
   'vLLM v1.0 — 10x Throughput, Stable APIs', 'Major refactor. 10x throughput on H100.',
   'simon-mo',     '{"upvotes":1620,"comments":198}','2026-02-15', '2026-02-15', 0.89,
   '{"hn_rank":2,"comments_top":"finally stable"}'),
  ('autogpt',         'hackernews',  'https://news.ycombinator.com/item?id=autogpt-platform','hn-autogpt-platform',    'launch',
   'AutoGPT Platform — Cloud-hosted Agent Builder', 'Spin up an AutoGPT in the cloud with a UI.',
   'siggravitas',  '{"upvotes":980,"comments":142}',  '2026-03-22', '2026-03-22', 0.82,
   '{"hn_rank":6,"comments_top":"open-core debate"}'),
  ('open-webui',      'hackernews',  'https://news.ycombinator.com/item?id=open-webui-2',    'hn-open-webui-2',         'launch',
   'Open WebUI 2.0 — Multi-user, RBAC, and Plugin Marketplace', 'Self-hosted ChatGPT-style UI with role-based access and 200+ community plugins.',
   'timothyylim',  '{"upvotes":1240,"comments":187}','2026-05-05', '2026-05-05', 0.87,
   '{"hn_rank":3,"comments_top":"great for self-hosters"}'),
  ('ragflow',         'hackernews',  'https://news.ycombinator.com/item?id=ragflow-graph',  'hn-ragflow-graph',        'major_update',
   'RAGFlow Adds GraphRAG and Agentic Retrieval', 'Native graph-based RAG with hybrid search.',
   'infini-flow',  '{"upvotes":780,"comments":108}',  '2026-04-19', '2026-04-19', 0.80,
   '{"hn_rank":8,"comments_top":"RAG is getting complex"}'),
  ('mistral',         'hackernews',  'https://news.ycombinator.com/item?id=mistral-large-3','hn-mistral-large-3',      'launch',
   'Mistral Large 3 — 300B MoE with Function Calling', 'Open weights, 256k context, top MMLU.',
   'arthurmensch', '{"upvotes":1980,"comments":312}','2026-02-03', '2026-02-03', 0.92,
   '{"hn_rank":2,"comments_top":"EU AI is real"}'),
  ('qwen',            'hackernews',  'https://news.ycombinator.com/item?id=qwen-3',          'hn-qwen-3',               'launch',
   'Qwen 3 — 1M Context, Open Weights', 'Alibaba releases Qwen 3 family with 1M context.',
   'alibaba-team', '{"upvotes":2120,"comments":298}','2026-04-29', '2026-04-29', 0.93,
   '{"hn_rank":1,"comments_top":"1M context, weights open"}'),
  ('claude',          'hackernews',  'https://news.ycombinator.com/item?id=claude-artifacts','hn-claude-artifacts',    'major_update',
   'Claude Artifacts Goes Standalone', 'Artifacts now has its own web app, shareable as URLs.',
   'anthropic-team','{"upvotes":2890,"comments":421}','2026-03-15', '2026-03-15', 0.95,
   '{"hn_rank":1,"comments_top":"wow, this is huge"}'),
  ('cursor',          'hackernews',  'https://news.ycombinator.com/item?id=cursor-tab',     'hn-cursor-tab',           'major_update',
   'Cursor Tab — Predictive Coding at the Speed of Thought', 'Tab key now predicts next edits with sub-100ms latency.',
   'cursor_team',  '{"upvotes":3140,"comments":521}','2026-02-24', '2026-02-24', 0.96,
   '{"hn_rank":1,"comments_top":"I cannot code without it"}'),
  ('claude',          'hackernews',  'https://news.ycombinator.com/item?id=claude-mcp',     'hn-claude-mcp',           'launch',
   'Model Context Protocol (MCP) 1.0', 'Anthropic proposes open standard for tool use. Adopted by OpenAI and Cursor.',
   'alexalbert',   '{"upvotes":4520,"comments":789}','2025-12-04', '2025-12-04', 0.97,
   '{"hn_rank":1,"comments_top":"this is the LSP moment for AI"}'),
  ('windsurf',        'hackernews',  'https://news.ycombinator.com/item?id=windsurf-agents','hn-windsurf-agents',      'launch',
   'Windsurf Agents — Long-running Dev Tasks', 'Spin up agents that work for hours in the background.',
   'codeium_team', '{"upvotes":1320,"comments":198}','2026-05-19', '2026-05-19', 0.89,
   '{"hn_rank":3,"comments_top":"really impressive demo"}'),
  ('llama',           'hackernews',  'https://news.ycombinator.com/item?id=llama-4',         'hn-llama-4',              'launch',
   'Llama 4 — Multimodal, Open Weights', 'Meta releases Llama 4 with native image and audio.',
   'meta_team',    '{"upvotes":2680,"comments":412}','2026-04-08', '2026-04-08', 0.94,
   '{"hn_rank":1,"comments_top":"open weights, multimodal"}'),
  ('openai',          'hackernews',  'https://news.ycombinator.com/item?id=o3-pro',          'hn-o3-pro',               'launch',
   'OpenAI o3-pro — 4-hour Reasoning', 'o3-pro solves ARC-AGI 2 and writes a 60-page paper from one prompt.',
   'openai_team',  '{"upvotes":3820,"comments":643}','2026-05-26', '2026-05-26', 0.96,
   '{"hn_rank":1,"comments_top":"AGI is closer than I thought"}'),
  ('gemini',          'hackernews',  'https://news.ycombinator.com/item?id=gemini-diffusion','hn-gemini-diffusion',     'launch',
   'Gemini Diffusion — Faster, Sometimes Smarter', 'Google ships a diffusion LLM, faster inference.',
   'google_team',  '{"upvotes":1640,"comments":231}','2026-03-04', '2026-03-04', 0.90,
   '{"hn_rank":3,"comments_top":"diffusion LLMs are real"}'),
  ('continue',        'hackernews',  'https://news.ycombinator.com/item?id=continue-1',     'hn-continue-1',           'launch',
   'Continue 1.0 — Open-source AI Code Assistant', 'Stable APIs and a marketplace for assistants.',
   'continuedev',  '{"upvotes":780,"comments":112}',  '2026-01-13', '2026-01-13', 0.79,
   '{"hn_rank":9,"comments_top":"amazing for OSS"}'),
  ('grok',            'hackernews',  'https://news.ycombinator.com/item?id=grok-3',          'hn-grok-3',               'major_update',
   'Grok 3 — Real-time Web Search Default', 'xAI makes Grok 3 the default on X.',
   'xai_team',     '{"upvotes":1420,"comments":198}','2026-02-19', '2026-02-19', 0.88,
   '{"hn_rank":4,"comments_top":"bias debates continue"}'),
  ('kimi',            'hackernews',  'https://news.ycombinator.com/item?id=kimi-k3',         'hn-kimi-k3',              'launch',
   'Kimi K3 — 2M Context for $1/million tokens', 'Moonshot AI drops API price 90%.',
   'moonshot_team','{"upvotes":1180,"comments":168}','2026-05-13', '2026-05-13', 0.87,
   '{"hn_rank":5,"comments_top":"$1/M is wild"}'),
  ('claude',          'hackernews',  'https://news.ycombinator.com/item?id=claude-cowork',  'hn-claude-cowork',        'launch',
   'Claude Cowork — Background Worker Agents', 'Anthropic ships long-running agents with file access.',
   'anthropic_team','{"upvotes":2240,"comments":312}','2026-04-30', '2026-04-30', 0.93,
   '{"hn_rank":1,"comments_top":"agents that actually finish"}'),
  ('kling',           'hackernews',  'https://news.ycombinator.com/item?id=kling-2',         'hn-kling-2',              'launch',
   'Kling 2.0 — 90-second 4K Video Generation', 'Kuaishou ships longer, sharper AI video.',
   'kuaishou_team','{"upvotes":980,"comments":141}',  '2026-05-22', '2026-05-22', 0.85,
   '{"hn_rank":6,"comments_top":"video gen keeps improving"}'),
  ('elevenlabs',      'hackernews',  'https://news.ycombinator.com/item?id=eleven-v3',      'hn-eleven-v3',            'major_update',
   'ElevenLabs v3 — Voice Design API', 'Design a new voice from a text description.',
   'eleven_team',  '{"upvotes":1280,"comments":178}','2026-04-22', '2026-04-22', 0.88,
   '{"hn_rank":4,"comments_top":"text-to-voice is wild"}'),
  ('suno',            'hackernews',  'https://news.ycombinator.com/item?id=suno-v5',         'hn-suno-v5',              'major_update',
   'Suno v5 — 4-minute Songs with Vocals', 'Suno ships full-length songs with multi-track stems.',
   'suno_team',    '{"upvotes":1980,"comments":324}','2026-03-29', '2026-03-29', 0.92,
   '{"hn_rank":2,"comments_top":"I made a banger in 30 seconds"}'),

  -- ===== github (25) =====
  ('openai',          'github',      'https://github.com/openai/whisper-v3',                'gh-openai-whisper-v3',    'open_source',
   'openai/whisper-v3 — 1.5B ASR with word-level timestamps', 'OpenAI ships Whisper v3 weights under MIT.',
   'openai',       '{"stars":18420,"forks":1920}',     '2026-02-08', '2026-02-08', 0.93,
   '{"topics":["asr","speech","multilingual"]}'),
  ('meta-llama',      'github',      'https://github.com/meta-llama/llama-4',               'gh-meta-llama-4',         'open_source',
   'meta-llama/llama-4 — Multimodal Foundation Model', 'Meta open-sources Llama 4 with image and audio.',
   'meta-llama',   '{"stars":32100,"forks":4100}',     '2026-04-09', '2026-04-09', 0.95,
   '{"topics":["llama","multimodal","open-source"]}'),
  ('deepseek-ai',     'github',      'https://github.com/deepseek-ai/DeepSeek-V4',         'gh-deepseek-v4',          'open_source',
   'deepseek-ai/DeepSeek-V4 — 1T MoE, open weights', 'Chinese lab open-sources a 1T MoE model.',
   'deepseek-ai',  '{"stars":24800,"forks":2680}',     '2026-01-20', '2026-01-20', 0.94,
   '{"topics":["moe","open-weights","chinese-llm"]}'),
  ('huggingface',     'github',      'https://github.com/huggingface/transformers-v5',     'gh-hf-transformers-v5',   'open_source',
   'huggingface/transformers-v5 — First-class MoE', 'Major refactor with native MoE and quantization.',
   'huggingface',  '{"stars":129000,"forks":25800}',   '2026-02-23', '2026-02-23', 0.96,
   '{"topics":["transformers","moe","nlp"]}'),
  ('langchain-ai',    'github',      'https://github.com/langchain-ai/langgraph-v2',       'gh-langgraph-v2',         'open_source',
   'langchain-ai/langgraph-v2 — Stateful Agents', 'Production-grade agent runtime.',
   'langchain-ai', '{"stars":14800,"forks":1820}',     '2026-01-27', '2026-01-27', 0.89,
   '{"topics":["agents","orchestration","python"]}'),
  ('ollama',          'github',      'https://github.com/ollama/ollama-vision',            'gh-ollama-vision',        'open_source',
   'ollama/ollama — Native Vision Support', 'Pull and run vision models locally.',
   'ollama',       '{"stars":92400,"forks":7100}',     '2026-04-12', '2026-04-12', 0.95,
   '{"topics":["llm","local","vision"]}'),
  ('vllm-project',    'github',      'https://github.com/vllm-project/vllm-v1',            'gh-vllm-v1',              'open_source',
   'vllm-project/vllm-v1 — 10x Throughput', 'Major refactor, 10x throughput on H100.',
   'vllm-project', '{"stars":28400,"forks":3800}',     '2026-02-16', '2026-02-16', 0.92,
   '{"topics":["inference","serving","paged-attention"]}'),
  ('open-webui',      'github',      'https://github.com/open-webui/open-webui-v2',        'gh-open-webui-v2',        'open_source',
   'open-webui/open-webui v2.0 — Multi-user, RBAC', 'Production-ready self-hostable chat UI.',
   'open-webui',   '{"stars":38600,"forks":4200}',     '2026-05-06', '2026-05-06', 0.93,
   '{"topics":["chat-ui","self-hosted","multi-user"]}'),
  ('anthropics',      'github',      'https://github.com/anthropics/claude-code-sdk',      'gh-claude-code-sdk',      'open_source',
   'anthropics/claude-code-sdk — Official SDK', 'Anthropic releases official SDK for Claude Code.',
   'anthropics',   '{"stars":8200,"forks":920}',       '2026-04-18', '2026-04-18', 0.88,
   '{"topics":["claude","sdk","agents"]}'),
  ('openai',          'github',      'https://github.com/openai/swarm',                     'gh-openai-swarm',         'open_source',
   'openai/swarm — Lightweight Multi-agent Framework', 'OpenAI releases Swarm for educational use.',
   'openai',       '{"stars":12200,"forks":1480}',     '2026-01-12', '2026-01-12', 0.84,
   '{"topics":["agents","multi-agent","lightweight"]}'),
  ('stability-ai',    'github',      'https://github.com/Stability-AI/sdxl-2',              'gh-stability-sdxl-2',     'open_source',
   'Stability-AI/sdxl-2 — Open Weights Image Model', 'SDXL 2 with photorealism and controllability.',
   'stability-ai', '{"stars":15800,"forks":2100}',     '2026-03-01', '2026-03-01', 0.90,
   '{"topics":["image","diffusion","open-weights"]}'),
  ('black-forest-labs','github',     'https://github.com/black-forest-labs/flux-2',         'gh-flux-2',               'open_source',
   'black-forest-labs/flux-2 — Open Weights Image Model', 'FLUX 2 matches proprietary models on benchmarks.',
   'black-forest-labs','{"stars":9400,"forks":1180}', '2026-02-12', '2026-02-12', 0.91,
   '{"topics":["image","diffusion","flux"]}'),
  ('qwen',            'github',      'https://github.com/QwenLM/Qwen3',                     'gh-qwen-3',               'open_source',
   'QwenLM/Qwen3 — 1M Context, Open Weights', 'Alibaba releases Qwen 3 with 1M context.',
   'QwenLM',       '{"stars":18600,"forks":2400}',     '2026-04-30', '2026-04-30', 0.94,
   '{"topics":["llm","open-weights","chinese"]}'),
  ('mistralai',       'github',      'https://github.com/mistralai/mistral-large-3',       'gh-mistral-large-3',      'open_source',
   'mistralai/mistral-large-3 — 300B MoE', 'Open weights Mistral Large 3 with 256k context.',
   'mistralai',    '{"stars":7400,"forks":980}',       '2026-02-04', '2026-02-04', 0.89,
   '{"topics":["llm","moe","european"]}'),
  ('google-deepmind', 'github',      'https://github.com/google-deepmind/gemini-3',         'gh-gemini-3',             'open_source',
   'google-deepmind/gemini-3 — Reference Implementations', 'Google open-sources Gemini 3 reference impls.',
   'google-deepmind','{"stars":11200,"forks":1640}',  '2026-04-26', '2026-04-26', 0.92,
   '{"topics":["gemini","multimodal","reasoning"]}'),
  ('moonshotai',      'github',      'https://github.com/MoonshotAI/Kimi-K3',               'gh-kimi-k3',              'open_source',
   'MoonshotAI/Kimi-K3 — 2M Context for $1/M', 'Long-context with extreme cost efficiency.',
   'MoonshotAI',   '{"stars":4800,"forks":620}',       '2026-05-14', '2026-05-14', 0.85,
   '{"topics":["llm","long-context","cost-effective"]}'),
  ('runwayml',        'github',      'https://github.com/runwayml/stable-video-2',         'gh-runway-sv2',           'open_source',
   'runwayml/stable-video-2 — 4-second 1080p clips', 'Open weights video model.',
   'runwayml',     '{"stars":6200,"forks":780}',       '2026-01-30', '2026-01-30', 0.86,
   '{"topics":["video","diffusion","open-weights"]}'),
  ('elevenlabs',      'github',      'https://github.com/elevenlabs/eleven-sdk',           'gh-eleven-sdk',           'open_source',
   'elevenlabs/eleven-sdk — Voice AI SDK', 'Official SDK for ElevenLabs APIs.',
   'elevenlabs',   '{"stars":2100,"forks":280}',       '2026-04-23', '2026-04-23', 0.82,
   '{"topics":["voice","sdk","multilingual"]}'),
  ('livekit',         'github',      'https://github.com/livekit/agents-v2',                'gh-livekit-agents-v2',    'open_source',
   'livekit/agents v2 — Voice AI in 50 lines', 'Real-time multimodal agents.',
   'livekit',      '{"stars":5400,"forks":620}',       '2026-02-19', '2026-02-19', 0.87,
   '{"topics":["voice","realtime","agents"]}'),
  ('comfyanonymous',  'github',      'https://github.com/comfyanonymous/comfyui-1-0',       'gh-comfyui-1-0',          'open_source',
   'comfyanonymous/comfyui 1.0 — Stable Diffusion UI', 'Production-ready node-based UI for image gen.',
   'comfyanonymous','{"stars":38600,"forks":4100}',    '2026-05-09', '2026-05-09', 0.94,
   '{"topics":["comfyui","ui","diffusion"]}'),
  ('suno-ai',         'github',      'https://github.com/suno-ai/suno-cogs',                'gh-suno-cogs',            'open_source',
   'suno-ai/suno-cogs — Open Music Model Components', 'Open-source training and inference recipes for music.',
   'suno-ai',      '{"stars":3400,"forks":410}',       '2026-03-30', '2026-03-30', 0.83,
   '{"topics":["music","audio","open-source"]}'),
  ('xai-org',         'github',      'https://github.com/xai-org/grok-3',                   'gh-grok-3',               'open_source',
   'xai-org/grok-3 — Reasoning Model Weights', 'xAI open-sources Grok 3 weights.',
   'xai-org',      '{"stars":8800,"forks":1120}',      '2026-02-20', '2026-02-20', 0.88,
   '{"topics":["grok","reasoning","open-weights"]}'),
  ('fireworks-ai',    'github',      'https://github.com/fireworks-ai/function-calling',   'gh-fireworks-fc',         'open_source',
   'fireworks-ai/function-calling — Production-grade tool use', 'Battle-tested function-calling stack.',
   'fireworks-ai', '{"stars":3200,"forks":410}',       '2026-04-26', '2026-04-26', 0.84,
   '{"topics":["function-calling","inference","tools"]}'),
  ('replicate',       'github',      'https://github.com/replicate/cog-2',                  'gh-replicate-cog-2',      'open_source',
   'replicate/cog 2.0 — Model packaging', 'Package any model with one Python decorator.',
   'replicate',    '{"stars":6800,"forks":720}',       '2026-01-23', '2026-01-23', 0.86,
   '{"topics":["cog","model-packaging","mlops"]}'),
  ('anthropics',      'github',      'https://github.com/anthropics/mcp-spec',              'gh-mcp-spec',             'open_source',
   'anthropics/mcp-spec — Model Context Protocol', 'Open standard for tool use.',
   'anthropics',   '{"stars":14600,"forks":1840}',     '2025-12-05', '2025-12-05', 0.95,
   '{"topics":["mcp","protocol","tools"]}'),

  -- ===== x (twitter) (20) =====
  ('sama',            'x',           'https://x.com/sama/status/1900000000000000001',       'x-sama-agi-2026',         'milestone',
   'Sam Altman on AGI roadmap', 'Sam Altman: "We are confident we know how to build AGI as we have traditionally understood it."',
   'sama',         '{"retweets":12400,"likes":98420,"replies":3280}', '2026-01-06', '2026-01-06', 0.92,
   '{"context":"AGI roadmap update"}'),
  ('ylecun',          'x',           'https://x.com/ylecun/status/1900000000000000002',     'x-lecun-jean-2026',       'milestone',
   'Yann LeCun on JEPA v3', 'Yann LeCun: "JEPA v3 is the foundation for the next generation of world-model AI."',
   'ylecun',       '{"retweets":8200,"likes":62100,"replies":2410}',  '2026-02-12', '2026-02-12', 0.88,
   '{"context":"World model announcement"}'),
  ('demishassabis',   'x',           'https://x.com/demishassabis/status/1900000000000003','x-deepmind-gemini-3',     'major_update',
   'Demis Hassabis on Gemini 3', 'Demis Hassabis: "Gemini 3 represents a step-change in reasoning and multimodality."',
   'demishassabis','{"retweets":14200,"likes":108400,"replies":3120}','2026-04-25', '2026-04-25', 0.96,
   '{"context":"Gemini 3 launch tweet"}'),
  ('sundarpichai',    'x',           'https://x.com/sundarpichai/status/1900000000000004', 'x-google-ai-mode',        'launch',
   'Sundar Pichai on AI Mode GA', 'Sundar Pichai: "AI Mode is now live in Google Search for everyone in the US."',
   'sundarpichai', '{"retweets":9800,"likes":78420,"replies":1820}',  '2026-05-14', '2026-05-14', 0.93,
   '{"context":"Google AI Mode GA"}'),
  ('elonmusk',        'x',           'https://x.com/elonmusk/status/1900000000000000005',  'x-grok-3-default',        'milestone',
   'Elon Musk on Grok 3 default', 'Elon Musk: "Grok 3 is now the default AI on X for all Premium users."',
   'elonmusk',     '{"retweets":32400,"likes":248000,"replies":8210}','2026-02-19', '2026-02-19', 0.94,
   '{"context":"Grok 3 default rollout"}'),
  ('satyanadella',    'x',           'https://x.com/satyanadella/status/1900000000000006', 'x-msft-copilot-wave-3',   'major_update',
   'Satya Nadella on Copilot Wave 3', 'Satya Nadella: "Copilot Wave 3 brings autonomous agents to every Microsoft 365 user."',
   'satyanadella', '{"retweets":11400,"likes":88200,"replies":2410}',  '2026-03-18', '2026-03-18', 0.92,
   '{"context":"Copilot Wave 3 launch"}'),
  ('maboroshi',       'x',           'https://x.com/maboroshi/status/1900000000000007',    'x-deepseek-r2',           'launch',
   'DeepSeek R2 launch tweet', 'DeepSeek: "R2 is now live. 90% cheaper than o3 at parity."',
   'maboroshi',    '{"retweets":14800,"likes":112000,"replies":4180}','2026-05-29', '2026-05-29', 0.95,
   '{"context":"DeepSeek R2 launch"}'),
  ('kimmonismus',     'x',           'https://x.com/kimmonismus/status/1900000000000008',  'x-kimi-k3-tweet',         'launch',
   'Moonshot AI on Kimi K3', 'Moonshot AI: "Kimi K3 with 2M context at $1/M tokens."',
   'kimmonismus',  '{"retweets":9800,"likes":74200,"replies":1840}',  '2026-05-13', '2026-05-13', 0.90,
   '{"context":"Kimi K3 pricing"}'),
  ('xai',             'x',           'https://x.com/xai/status/1900000000000009',          'x-xai-coding-model',      'launch',
   'xAI on Grok Coder', 'xAI: "Grok Coder — our first model trained for code."',
   'xai',          '{"retweets":8200,"likes":62100,"replies":1820}',  '2026-04-04', '2026-04-04', 0.87,
   '{"context":"Grok Coder release"}'),
  ('openai',          'x',           'https://x.com/openai/status/1900000000000010',       'x-openai-devday-2026',    'launch',
   'OpenAI DevDay 2026 announcements', 'OpenAI DevDay 2026: "Agents, Apps, and the new Responses API."',
   'openai',       '{"retweets":21200,"likes":168000,"replies":4820}','2026-04-30', '2026-04-30', 0.96,
   '{"context":"DevDay announcements"}'),
  ('a16z',            'x',           'https://x.com/a16z/status/1900000000000011',         'x-a16z-ai-thesis-2026',   'milestone',
   'a16z 2026 AI thesis', 'a16z: "Our 2026 AI thesis: agents, voice, and vertical SaaS are eating the stack."',
   'a16z',         '{"retweets":6400,"likes":48200,"replies":1240}',  '2026-01-15', '2026-01-15', 0.85,
   '{"context":"a16z AI thesis"}'),
  ('sequoia',         'x',           'https://x.com/sequoia/status/1900000000000012',      'x-sequoia-ai-2026',       'milestone',
   'Sequoia AI report', 'Sequoia: "The AI build cycle is accelerating — 3x more agent-first startups in 2026."',
   'sequoia',      '{"retweets":5800,"likes":42100,"replies":980}',   '2026-02-04', '2026-02-04', 0.84,
   '{"context":"Sequoia AI report"}'),
  ('ylecun',          'x',           'https://x.com/ylecun/status/1900000000000013',      'x-lecun-world-model',     'milestone',
   'Yann LeCun on Cosmos v2', 'Yann LeCun: "World models are the next frontier — Meta releases Cosmos v2."',
   'ylecun',       '{"retweets":7200,"likes":52100,"replies":1420}',  '2026-04-18', '2026-04-18', 0.89,
   '{"context":"Cosmos v2 release"}'),
  ('miramurati',      'x',           'https://x.com/miramurati/status/1900000000000014',   'x-mira-thinking-machines', 'launch',
   'Mira Murati on Thinking Machines', 'Mira Murati: "Thinking Machines is building the next generation of interpretable AI."',
   'miramurati',   '{"retweets":11800,"likes":88400,"replies":2410}', '2026-03-15', '2026-03-15', 0.90,
   '{"context":"Thinking Machines launch"}'),
  ('feifei_li',       'x',           'https://x.com/feifei_li/status/1900000000000015',    'x-feifei-spatial',        'milestone',
   'Fei-Fei Li on spatial intelligence', 'Fei-Fei Li: "Spatial intelligence is the next chapter of AI."',
   'feifei_li',    '{"retweets":9400,"likes":72100,"replies":1840}',  '2026-05-20', '2026-05-20', 0.91,
   '{"context":"World Labs update"}'),
  ('arankomatsuzaki', 'x',           'https://x.com/arankomatsuzaki/status/1900000000000016','x-arxiv-spotlight-mamba','milestone',
   'Aravind on Mamba-3', 'arankomatsuzaki: "Mamba-3 is now competitive with transformers at 1M context."',
   'arankomatsuzaki','{"retweets":4200,"likes":31200,"replies":820}','2026-02-25', '2026-02-25', 0.82,
   '{"context":"Mamba-3 research"}'),
  ('karpathy',        'x',           'https://x.com/karpathy/status/1900000000000017',     'x-karpathy-llm-school',   'milestone',
   'LLM School relaunch',
   'Andrej Karpathy: "LLM School is back — 30 hours of new content, free."',
   'karpathy',     '{"retweets":12800,"likes":102400,"replies":2410}','2026-04-10', '2026-04-10', 0.93,
   '{"context":"Educational content"}'),
  ('daboroshi',       'x',           'https://x.com/daboroshi/status/1900000000000018',    'x-japanese-llm',          'launch',
   'Swallow-2 release',
   'Japanese LLM consortium: "We release Swallow-2 — 70B params, top on JGLUE."',
   'daboroshi',    '{"retweets":3200,"likes":24100,"replies":680}',   '2026-05-08', '2026-05-08', 0.81,
   '{"context":"Swallow-2 release"}'),
  ('ylecun',          'x',           'https://x.com/ylecun/status/1900000000000019',      'x-lecun-energy-llm',      'milestone',
   'LLM energy efficiency gains',
   'Yann LeCun: "LLM energy efficiency improved 100x in 24 months."',
   'ylecun',       '{"retweets":6800,"likes":52100,"replies":1420}',  '2026-05-25', '2026-05-25', 0.86,
   '{"context":"Energy efficiency"}'),
  ('demishassabis',   'x',           'https://x.com/demishassabis/status/1900000000000020','x-deepmind-drug',         'milestone',
   'Isomorphic Phase 3 trials',
   'Demis Hassabis: "Isomorphic Labs enters Phase 3 trials with AI-designed drug."',
   'demishassabis','{"retweets":14200,"likes":112000,"replies":3210}','2026-04-12', '2026-04-12', 0.94,
   '{"context":"AI in pharma"}'),

  -- ===== arxiv (15) =====
  ('anthropic-paper', 'arxiv',       'https://arxiv.org/abs/2601.00001',                     'arxiv-claude-cot',        'milestone',
   'Constitutional AI Revisited: Training Harmless, Helpful, and Honest LLMs at Scale',
   'New research paper from Anthropic Research on arxiv.',
   'Anthropic Research', '{"citations":42,"downloads":18420}', '2026-01-10', '2026-01-10', 0.85,
   '{"arxiv_id":"2601.00001","category":"cs.CL"}'),
  ('openai-paper',    'arxiv',       'https://arxiv.org/abs/2601.00002',                     'arxiv-o3-reasoning',      'milestone',
   'Test-time Compute Scaling Laws for Reasoning Models',
   'New research paper from OpenAI Research on arxiv.',
   'OpenAI Research',   '{"citations":68,"downloads":24100}', '2026-01-22', '2026-01-22', 0.92,
   '{"arxiv_id":"2601.00002","category":"cs.AI"}'),
  ('deepseek-paper',  'arxiv',       'https://arxiv.org/abs/2601.00003',                     'arxiv-deepseek-moe',      'milestone',
   'Efficient MoE Training with 1% Activation',
   'New research paper from DeepSeek Research on arxiv.',
   'DeepSeek Research','{"citations":124,"downloads":31200}','2026-02-14', '2026-02-14', 0.94,
   '{"arxiv_id":"2601.00003","category":"cs.LG"}'),
  ('google-paper',    'arxiv',       'https://arxiv.org/abs/2601.00004',                     'arxiv-gemini-multimodal', 'milestone',
   'Native Multimodal Training for Foundation Models',
   'New research paper from Google DeepMind on arxiv.',
   'Google DeepMind',   '{"citations":56,"downloads":19400}','2026-03-08', '2026-03-08', 0.91,
   '{"arxiv_id":"2601.00004","category":"cs.CV"}'),
  ('meta-paper',      'arxiv',       'https://arxiv.org/abs/2601.00005',                     'arxiv-llama-multimodal',  'milestone',
   'Llama 4: Open Weights Multimodal Foundation Model',
   'New research paper from Meta FAIR on arxiv.',
   'Meta FAIR',         '{"citations":78,"downloads":22800}','2026-04-09', '2026-04-09', 0.93,
   '{"arxiv_id":"2601.00005","category":"cs.CL"}'),
  ('mit-paper',       'arxiv',       'https://arxiv.org/abs/2601.00006',                     'arxiv-imagenet-2026',     'milestone',
   'Scaling Laws for Diffusion Image Generation Beyond 1B Parameters',
   'New research paper from MIT CSAIL on arxiv.',
   'MIT CSAIL',         '{"citations":34,"downloads":14200}','2026-04-22', '2026-04-22', 0.85,
   '{"arxiv_id":"2601.00006","category":"cs.CV"}'),
  ('stanford-paper',  'arxiv',       'https://arxiv.org/abs/2601.00007',                     'arxiv-agent-bench',      'milestone',
   'GAIA-X: A Benchmark for General AI Assistants in the Real World',
   'New research paper from Stanford CRFM on arxiv.',
   'Stanford CRFM',     '{"citations":48,"downloads":16800}','2026-05-04', '2026-05-04', 0.88,
   '{"arxiv_id":"2601.00007","category":"cs.AI"}'),
  ('mistral-paper',   'arxiv',       'https://arxiv.org/abs/2601.00008',                     'arxiv-mistral-moe',      'milestone',
   'Routing Strategies for Sparse Mixture of Experts',
   'New research paper from Mistral Research on arxiv.',
   'Mistral Research',  '{"citations":62,"downloads":19200}','2026-02-04', '2026-02-04', 0.89,
   '{"arxiv_id":"2601.00008","category":"cs.LG"}'),
  ('openai-paper-2',  'arxiv',       'https://arxiv.org/abs/2601.00009',                     'arxiv-dpo-2026',         'milestone',
   'Direct Preference Optimization: A Decade in Review',
   'New research paper from OpenAI Research on arxiv.',
   'OpenAI Research',   '{"citations":84,"downloads":28400}','2026-03-18', '2026-03-18', 0.92,
   '{"arxiv_id":"2601.00009","category":"cs.LG"}'),
  ('berkeley-paper',  'arxiv',       'https://arxiv.org/abs/2601.00010',                     'arxiv-llm-eval',         'milestone',
   'LLM Evaluation in 2026: A Practical Guide for Practitioners',
   'New research paper from UC Berkeley on arxiv.',
   'UC Berkeley',       '{"citations":28,"downloads":11800}','2026-05-15', '2026-05-15', 0.83,
   '{"arxiv_id":"2601.00010","category":"cs.CL"}'),
  ('anthropic-paper-2','arxiv',      'https://arxiv.org/abs/2601.00011',                     'arxiv-mec-interp',       'milestone',
   'Scaling Monosemanticity: Interpreting Claude 3 at 10x Larger Scale',
   'New research paper from Anthropic Research on arxiv.',
   'Anthropic Research','{"citations":52,"downloads":22100}','2026-04-28', '2026-04-28', 0.91,
   '{"arxiv_id":"2601.00011","category":"cs.AI"}'),
  ('nvidia-paper',    'arxiv',       'https://arxiv.org/abs/2601.00012',                     'arxiv-tensorrt-llm',     'milestone',
   'TensorRT-LLM v2: 5x Faster Inference for Production Workloads',
   'New research paper from NVIDIA Research on arxiv.',
   'NVIDIA Research',   '{"citations":44,"downloads":16400}','2026-03-26', '2026-03-26', 0.86,
   '{"arxiv_id":"2601.00012","category":"cs.PF"}'),
  ('microsoft-paper', 'arxiv',       'https://arxiv.org/abs/2601.00013',                     'arxiv-orca-3',           'milestone',
   'Orca 3: Agentic Foundation Models for Real-world Tasks',
   'New research paper from Microsoft Research on arxiv.',
   'Microsoft Research','{"citations":36,"downloads":14200}','2026-04-15', '2026-04-15', 0.85,
   '{"arxiv_id":"2601.00013","category":"cs.AI"}'),
  ('tsinghua-paper',  'arxiv',       'https://arxiv.org/abs/2601.00014',                     'arxiv-chinese-llm',      'milestone',
   'A Survey of Chinese LLMs: From 2020 to 2026',
   'New research paper from Tsinghua AIR on arxiv.',
   'Tsinghua AIR',       '{"citations":64,"downloads":19800}','2026-05-09', '2026-05-09', 0.88,
   '{"arxiv_id":"2601.00014","category":"cs.CL"}'),
  ('openreview-paper','arxiv',       'https://arxiv.org/abs/2601.00015',                     'arxiv-rlhf-2026',        'milestone',
   'RLHF in 2026: A Year of Breakthroughs and Open Questions',
   'New research paper from Multiple Institutions on arxiv.',
   'Multiple Institutions','{"citations":58,"downloads":18200}','2026-05-22', '2026-05-22', 0.87,
   '{"arxiv_id":"2601.00015","category":"cs.LG"}'),

  -- ===== xiaohongshu (5) =====
  ('doubao',          'xiaohongshu', 'https://www.xiaohongshu.com/discovery/item/doubao-2',  'xhs-doubao-2',            'launch',
   '豆包 2.0 上线 — 接入字节跳动全系 App',
   'Trending on Xiaohongshu, posted by doubao_team.',
   'doubao_team',  '{"likes":18420,"collects":8240,"comments":2410}', '2026-03-15', '2026-03-15', 0.88,
   '{"topic":"AI助手","rank":1}'),
  ('hunyuan',         'xiaohongshu', 'https://www.xiaohongshu.com/discovery/item/hunyuan-3d','xhs-hunyuan-3d',          'launch',
   '腾讯混元 3D — 一句话生成 3D 模型',
   'Trending on Xiaohongshu, posted by hunyuan_team.',
   'hunyuan_team', '{"likes":12200,"collects":6820,"comments":1820}', '2026-04-08', '2026-04-08', 0.86,
   '{"topic":"3D生成","rank":2}'),
  ('kimi',            'xiaohongshu', 'https://www.xiaohongshu.com/discovery/item/kimi-search-2','xhs-kimi-search-2',    'major_update',
   'Kimi 搜索 2.0 — 接入微信公众号全文',
   'Trending on Xiaohongshu, posted by kimi_team.',
   'kimi_team',    '{"likes":9800,"collects":4200,"comments":1240}',  '2026-05-12', '2026-05-12', 0.85,
   '{"topic":"AI搜索","rank":3}'),
  ('manus',           'xiaohongshu', 'https://www.xiaohongshu.com/discovery/item/manus-promo','xhs-manus-promo',         'milestone',
   'Manus — 邀请内测 7 天, 1.5 亿人申请',
   'Trending on Xiaohongshu, posted by manus_team.',
   'manus_team',   '{"likes":24100,"collects":11200,"comments":4820}','2026-03-08', '2026-03-08', 0.92,
   '{"topic":"AI智能体","rank":1}'),
  ('qwen',            'xiaohongshu', 'https://www.xiaohongshu.com/discovery/item/qwen-free',  'xhs-qwen-free',           'launch',
   '通义千问 Qwen 3 — 1M 上下文免费开放',
   'Trending on Xiaohongshu, posted by qwen_team.',
   'qwen_team',    '{"likes":18420,"collects":8210,"comments":2480}', '2026-05-01', '2026-05-01', 0.91,
   '{"topic":"开源大模型","rank":1}'),

  -- ===== funding (5) within launch_events to consolidate =====
  ('manus',           'github',      'https://github.com/manus-ai/manus-funding',            'gh-manus-funding',        'funding',
   'Manus raises $75M Series B at $1B valuation',
   'Funding announcement from manus_team.',
   'manus_team',   '{"stars":0,"forks":0}',            '2026-05-20', '2026-05-20', 0.90,
   '{"round":"Series B","amount":"$75M","lead":"HSG"}'),
  ('elevenlabs',      'github',      'https://github.com/elevenlabs/eleven-funding',         'gh-eleven-funding',       'funding',
   'ElevenLabs raises $200M Series D at $6B valuation',
   'Funding announcement from elevenlabs.',
   'elevenlabs',   '{"stars":0,"forks":0}',            '2026-04-25', '2026-04-25', 0.92,
   '{"round":"Series D","amount":"$200M","lead":"Sequoia"}'),
  ('replicate',       'github',      'https://github.com/replicate/replicate-funding',       'gh-replicate-funding',    'funding',
   'Replicate raises $40M Series B from a16z',
   'Funding announcement from replicate.',
   'replicate',    '{"stars":0,"forks":0}',            '2026-03-12', '2026-03-12', 0.88,
   '{"round":"Series B","amount":"$40M","lead":"a16z"}'),
  ('suno',            'github',      'https://github.com/suno-ai/suno-funding',              'gh-suno-funding',         'funding',
   'Suno raises $125M Series C at $2.45B valuation',
   'Funding announcement from suno_team.',
   'suno_team',    '{"stars":0,"forks":0}',            '2026-02-28', '2026-02-28', 0.91,
   '{"round":"Series C","amount":"$125M","lead":"Lightspeed"}'),
  ('heygen',          'github',      'https://github.com/heygen/heygen-funding',             'gh-heygen-funding',       'funding',
   'HeyGen raises $60M Series C+ extension',
   'Funding announcement from heygen_team.',
   'heygen_team',  '{"stars":0,"forks":0}',            '2026-04-18', '2026-04-18', 0.86,
   '{"round":"Series C+","amount":"$60M","lead":"BOND"}')
) AS e(product_slug, source, source_url, source_id, event_type, title, body, author, engagement, detected_at, event_at, confidence, raw_data)
JOIN products p ON p.slug = e.product_slug
ON CONFLICT (source, source_id) DO UPDATE SET
  title = EXCLUDED.title,
  body = EXCLUDED.body,
  engagement = EXCLUDED.engagement,
  confidence = EXCLUDED.confidence,
  updated_at = NOW();

-- 验证
DO $$
DECLARE
  v_count INTEGER;
  v_sources INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM launch_events;
  SELECT COUNT(DISTINCT source) INTO v_sources FROM launch_events;
  RAISE NOTICE 'seed-phase-e-launch-events-120: % events from % sources', v_count, v_sources;
END $$;

-- ANALYZE
ANALYZE launch_events;
