/**
 * AI Radar Seed Script
 * Generates SQL INSERT statements for 50+ realistic AI products.
 *
 * Run with: bun run supabase/seed.ts  > supabase/seed.sql
 * Or:       npx tsx supabase/seed.ts  > supabase/seed.sql
 */

// ── helpers ──────────────────────────────────────────────────────────
const esc = (s: string | null) => (s === null ? 'NULL' : `'${s.replace(/'/g, "''")}'`);
const arr = (a: string[]) => (a.length ? `ARRAY[${a.map(esc).join(',')}]` : 'ARRAY[]::text[]');
const obj = (o: Record<string, unknown>) =>
  `'${JSON.stringify(o).replace(/'/g, "''")}'`;

interface ProductSeed {
  slug: string;
  name: string;
  name_en?: string;
  name_zh?: string;
  description?: string;
  description_en?: string;
  description_zh?: string;
  website_url?: string;
  github_url?: string;
  logo_url?: string;
  category?: string;
  subcategory?: string;
  tags?: string[];
  tech_stack?: string[];
  pricing_model?: 'free' | 'freemium' | 'paid' | 'open_source';
  pricing_url?: string;
  availability_status?: 'active' | 'low_active' | 'inactive' | 'dead';
  commercialization_status?: string;
  funding_stage?: string;
  founder_info?: string;
  launch_date?: string;
  confidence_score?: number;
  confidence_level?: 'high' | 'medium' | 'low' | 'unverified';
  validation_signals?: Record<string, unknown>;
  source_count?: number;
  weekly_growth_rate?: number;
  monthly_growth_rate?: number;
  github_stars?: number;
}

// ── product data ─────────────────────────────────────────────────────
const products: ProductSeed[] = [
  // ─── LLM / Chatbots (1-10) ───
  {
    slug: 'chatgpt',
    name: 'ChatGPT',
    name_en: 'ChatGPT',
    name_zh: 'ChatGPT',
    description_en: 'OpenAI\'s conversational AI assistant powered by GPT-4o and later models.',
    description_zh: 'OpenAI 推出的对话式 AI 助手，基于 GPT-4o 及更新模型。',
    website_url: 'https://chatgpt.com',
    category: 'LLM',
    subcategory: 'Chatbot',
    tags: ['chatbot', 'generative-ai', 'conversational-ai', 'multimodal'],
    tech_stack: ['Python', 'PyTorch', 'Kubernetes'],
    pricing_model: 'freemium',
    pricing_url: 'https://openai.com/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial — 200M+ weekly active users',
    funding_stage: 'Series (Microsoft-backed)',
    founder_info: 'Sam Altman, Greg Brockman, Ilya Sutskever',
    launch_date: '2022-11-30',
    confidence_score: 98,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 15,
    weekly_growth_rate: 2.1,
    monthly_growth_rate: 8.5,
  },
  {
    slug: 'claude',
    name: 'Claude',
    name_en: 'Claude',
    name_zh: 'Claude',
    description_en: 'Anthropic\'s AI assistant with long context windows and advanced reasoning (Claude 3.5/4).',
    description_zh: 'Anthropic 的 AI 助手，支持超长上下文和高级推理能力。',
    website_url: 'https://claude.ai',
    category: 'LLM',
    subcategory: 'Chatbot',
    tags: ['chatbot', 'generative-ai', 'long-context', 'reasoning'],
    tech_stack: ['Python', 'JAX'],
    pricing_model: 'freemium',
    pricing_url: 'https://www.anthropic.com/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series D ($8B+ valuation)',
    founder_info: 'Dario Amodei, Daniela Amodei',
    launch_date: '2023-03-14',
    confidence_score: 97,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 14,
    weekly_growth_rate: 3.2,
    monthly_growth_rate: 12.1,
  },
  {
    slug: 'gemini',
    name: 'Gemini',
    name_en: 'Gemini',
    name_zh: 'Gemini',
    description_en: 'Google\'s multimodal AI model family, available via Gemini app and API.',
    description_zh: 'Google 的多模态 AI 模型系列，可通过 Gemini 应用和 API 使用。',
    website_url: 'https://gemini.google.com',
    github_url: 'https://github.com/google/generative-ai-docs',
    category: 'LLM',
    subcategory: 'Foundation Model',
    tags: ['multimodal', 'generative-ai', 'google', 'foundation-model'],
    tech_stack: ['Python', 'TensorFlow', 'TPU'],
    pricing_model: 'freemium',
    pricing_url: 'https://ai.google.dev/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Internal (Google/Alphabet)',
    founder_info: 'Google DeepMind',
    launch_date: '2023-12-06',
    confidence_score: 96,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 13,
    weekly_growth_rate: 1.8,
    monthly_growth_rate: 7.2,
  },
  {
    slug: 'qwen',
    name: '通义千问',
    name_en: 'Qwen',
    name_zh: '通义千问',
    description_en: 'Alibaba\'s large language model series, open-source and API available.',
    description_zh: '阿里巴巴推出的大语言模型系列，提供开源和 API 服务。',
    website_url: 'https://tongyi.aliyun.com',
    github_url: 'https://github.com/QwenLM/Qwen',
    category: 'LLM',
    subcategory: 'Foundation Model',
    tags: ['open-source', 'chinese-llm', 'foundation-model', 'multimodal'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'freemium',
    pricing_url: 'https://help.aliyun.com/zh/model-studio',
    availability_status: 'active',
    commercialization_status: 'Commercial + Open Source',
    funding_stage: 'Internal (Alibaba)',
    founder_info: 'Alibaba Cloud / 阿里云',
    launch_date: '2023-04-07',
    confidence_score: 93,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 11,
    weekly_growth_rate: 2.5,
    monthly_growth_rate: 10.3,
    github_stars: 18000,
  },
  {
    slug: 'deepseek',
    name: 'DeepSeek',
    name_en: 'DeepSeek',
    name_zh: '深度求索',
    description_en: 'Chinese AI company known for open-source LLMs and efficient training (DeepSeek-V3, R1).',
    description_zh: '中国 AI 公司，以开源大模型和高效训练著称。',
    website_url: 'https://deepseek.com',
    github_url: 'https://github.com/deepseek-ai',
    category: 'LLM',
    subcategory: 'Foundation Model',
    tags: ['open-source', 'chinese-llm', 'reasoning', 'cost-effective'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'free',
    availability_status: 'active',
    commercialization_status: 'Commercial + Open Source',
    funding_stage: 'Series (High-Flyer backed)',
    founder_info: '梁文锋 (Liang Wenfeng)',
    launch_date: '2023-06-01',
    confidence_score: 94,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 12,
    weekly_growth_rate: 5.8,
    monthly_growth_rate: 22.0,
    github_stars: 15000,
  },
  {
    slug: 'llama',
    name: 'Llama',
    name_en: 'Llama',
    name_zh: 'Llama',
    description_en: 'Meta\'s open-source LLM family (Llama 3/3.1/3.2/4), powering countless downstream projects.',
    description_zh: 'Meta 的开源大模型家族，驱动了无数下游项目。',
    website_url: 'https://llama.meta.com',
    github_url: 'https://github.com/meta-llama/llama',
    category: 'LLM',
    subcategory: 'Foundation Model',
    tags: ['open-source', 'foundation-model', 'meta', 'multimodal'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'open_source',
    pricing_url: 'https://llama.meta.com/llama3/license/',
    availability_status: 'active',
    commercialization_status: 'Open Source (custom license)',
    funding_stage: 'Internal (Meta)',
    founder_info: 'Meta AI Research',
    launch_date: '2023-02-24',
    confidence_score: 96,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 14,
    weekly_growth_rate: 1.5,
    monthly_growth_rate: 6.0,
    github_stars: 56000,
  },
  {
    slug: 'mistral',
    name: 'Mistral AI',
    name_en: 'Mistral AI',
    name_zh: 'Mistral AI',
    description_en: 'French AI company building efficient open-weight LLMs (Mistral 7B, Mixtral, Mistral Large).',
    description_zh: '法国 AI 公司，构建高效的开源权重大模型。',
    website_url: 'https://mistral.ai',
    github_url: 'https://github.com/mistralai',
    category: 'LLM',
    subcategory: 'Foundation Model',
    tags: ['open-source', 'european-ai', 'efficient-llm'],
    tech_stack: ['Python', 'PyTorch', 'JAX'],
    pricing_model: 'freemium',
    pricing_url: 'https://mistral.ai/technology/#pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial + Open Weight',
    funding_stage: 'Series B (~$6B valuation)',
    founder_info: 'Arthur Mensch, Timothée Lacroix, Guillaume Lample',
    launch_date: '2023-04-01',
    confidence_score: 90,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 9,
    weekly_growth_rate: 2.0,
    monthly_growth_rate: 8.0,
    github_stars: 12000,
  },
  {
    slug: 'grok',
    name: 'Grok',
    name_en: 'Grok',
    name_zh: 'Grok',
    description_en: 'xAI\'s conversational AI integrated with X (Twitter), known for real-time knowledge.',
    description_zh: 'xAI 的对话式 AI，集成于 X（推特），以实时知识著称。',
    website_url: 'https://grok.com',
    category: 'LLM',
    subcategory: 'Chatbot',
    tags: ['chatbot', 'real-time', 'x-platform'],
    tech_stack: ['Python', 'JAX'],
    pricing_model: 'paid',
    availability_status: 'active',
    commercialization_status: 'Commercial (X Premium)',
    funding_stage: 'Series ($24B+ valuation)',
    founder_info: 'Elon Musk',
    launch_date: '2023-11-04',
    confidence_score: 88,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 8,
    weekly_growth_rate: 1.2,
    monthly_growth_rate: 5.0,
  },
  {
    slug: 'kimi',
    name: 'Kimi',
    name_en: 'Kimi',
    name_zh: 'Kimi 智能助手',
    description_en: 'Moonshot AI\'s conversational assistant with ultra-long context window (200K+ tokens).',
    description_zh: '月之暗面推出的对话助手，支持超长上下文窗口。',
    website_url: 'https://kimi.moonshot.cn',
    github_url: 'https://github.com/MoonshotAI',
    category: 'LLM',
    subcategory: 'Chatbot',
    tags: ['chinese-llm', 'long-context', 'chatbot'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'freemium',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series C',
    founder_info: '杨植麟 (Yang Zhilin)',
    launch_date: '2023-10-01',
    confidence_score: 89,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 7,
    weekly_growth_rate: 2.8,
    monthly_growth_rate: 11.0,
  },
  {
    slug: 'ernie-bot',
    name: '文心一言',
    name_en: 'ERNIE Bot',
    name_zh: '文心一言',
    description_en: 'Baidu\'s large language model, integrated across Baidu\'s product ecosystem.',
    description_zh: '百度推出的大语言模型，深度集成于百度产品生态。',
    website_url: 'https://yiyan.baidu.com',
    category: 'LLM',
    subcategory: 'Chatbot',
    tags: ['chinese-llm', 'baidu', 'enterprise'],
    tech_stack: ['Python', 'PaddlePaddle'],
    pricing_model: 'freemium',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Internal (Baidu)',
    founder_info: 'Baidu / 百度',
    launch_date: '2023-03-27',
    confidence_score: 86,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 6,
    weekly_growth_rate: 0.8,
    monthly_growth_rate: 3.2,
  },

  // ─── AI Coding Assistants (11-18) ───
  {
    slug: 'github-copilot',
    name: 'GitHub Copilot',
    name_en: 'GitHub Copilot',
    name_zh: 'GitHub Copilot',
    description_en: 'AI pair programmer powered by OpenAI Codex and GPT models, integrated into VS Code and JetBrains.',
    description_zh: 'AI 编程助手，基于 OpenAI Codex 和 GPT 模型，集成于 VS Code 和 JetBrains。',
    website_url: 'https://github.com/features/copilot',
    category: 'AI Coding',
    subcategory: 'Code Completion',
    tags: ['code-generation', 'developer-tools', 'ide-extension', 'github'],
    tech_stack: ['TypeScript', 'Python', 'OpenAI API'],
    pricing_model: 'paid',
    pricing_url: 'https://github.com/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial (Microsoft/GitHub)',
    funding_stage: 'Internal (Microsoft)',
    founder_info: 'GitHub / Microsoft',
    launch_date: '2021-06-29',
    confidence_score: 97,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 13,
    weekly_growth_rate: 1.5,
    monthly_growth_rate: 6.0,
  },
  {
    slug: 'cursor',
    name: 'Cursor',
    name_en: 'Cursor',
    name_zh: 'Cursor',
    description_en: 'AI-first code editor built for pair-programming with AI, fork of VS Code.',
    description_zh: '以 AI 为核心的代码编辑器，基于 VS Code 分叉构建。',
    website_url: 'https://cursor.com',
    category: 'AI Coding',
    subcategory: 'AI IDE',
    tags: ['ai-ide', 'code-generation', 'developer-tools', 'fork-vscode'],
    tech_stack: ['TypeScript', 'Electron', 'LSP'],
    pricing_model: 'freemium',
    pricing_url: 'https://cursor.com/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series B ($2.8B valuation)',
    founder_info: 'Michael Truong, Anyscript',
    launch_date: '2022-09-01',
    confidence_score: 93,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 11,
    weekly_growth_rate: 4.5,
    monthly_growth_rate: 18.0,
  },
  {
    slug: 'windsurf',
    name: 'Windsurf',
    name_en: 'Windsurf',
    name_zh: 'Windsurf',
    description_en: 'AI IDE by Codeium (now Windsurf) with agentic coding capabilities and deep codebase understanding.',
    description_zh: 'Codeium 推出的 AI IDE，支持智能体编程和深度代码理解。',
    website_url: 'https://windsurf.com',
    category: 'AI Coding',
    subcategory: 'AI IDE',
    tags: ['ai-ide', 'code-completion', 'developer-tools'],
    tech_stack: ['TypeScript', 'Rust', 'LSP'],
    pricing_model: 'freemium',
    pricing_url: 'https://windsurf.com/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series B',
    founder_info: 'Codeium / Windsurf Inc.',
    launch_date: '2024-05-01',
    confidence_score: 87,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 8,
    weekly_growth_rate: 3.8,
    monthly_growth_rate: 15.0,
  },
  {
    slug: 'cline',
    name: 'Cline',
    name_en: 'Cline',
    name_zh: 'Cline',
    description_en: 'Open-source autonomous coding agent for VS Code, capable of complex multi-step tasks.',
    description_zh: 'VS Code 的开源自主编程智能体，可处理复杂多步骤任务。',
    github_url: 'https://github.com/cline/cline',
    category: 'AI Coding',
    subcategory: 'Coding Agent',
    tags: ['open-source', 'coding-agent', 'vscode-extension', 'autonomous'],
    tech_stack: ['TypeScript', 'OpenRouter'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source',
    funding_stage: 'Open Source',
    founder_info: 'Community / Cline',
    launch_date: '2024-03-15',
    confidence_score: 85,
    confidence_level: 'high',
    validation_signals: { github: true, media_coverage: true },
    source_count: 6,
    weekly_growth_rate: 5.0,
    monthly_growth_rate: 20.0,
    github_stars: 32000,
  },
  {
    slug: 'continue',
    name: 'Continue',
    name_en: 'Continue',
    name_zh: 'Continue',
    description_en: 'Open-source AI code assistant plugin for VS Code and JetBrains, supports multiple LLM backends.',
    description_zh: '开源 AI 代码助手插件，支持 VS Code 和 JetBrains，多 LLM 后端。',
    website_url: 'https://continue.dev',
    github_url: 'https://github.com/continuedev/continue',
    category: 'AI Coding',
    subcategory: 'Code Assistant',
    tags: ['open-source', 'code-completion', 'vscode-extension', 'jetbrains'],
    tech_stack: ['TypeScript', 'Python'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source + Enterprise',
    funding_stage: 'Seed',
    founder_info: 'Continue Dev Inc.',
    launch_date: '2023-01-01',
    confidence_score: 86,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 7,
    weekly_growth_rate: 2.5,
    monthly_growth_rate: 10.0,
    github_stars: 20000,
  },
  {
    slug: 'codex-cli',
    name: 'OpenAI Codex CLI',
    name_en: 'Codex CLI',
    name_zh: 'Codex CLI',
    description_en: 'OpenAI\'s open-source coding agent running in the terminal, based on o3/o4-mini models.',
    description_zh: 'OpenAI 推出的开源终端编程智能体。',
    github_url: 'https://github.com/openai/codex',
    category: 'AI Coding',
    subcategory: 'Coding Agent',
    tags: ['open-source', 'coding-agent', 'terminal', 'openai'],
    tech_stack: ['TypeScript', 'Rust'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source',
    funding_stage: 'Internal (OpenAI)',
    founder_info: 'OpenAI',
    launch_date: '2025-03-01',
    confidence_score: 90,
    confidence_level: 'high',
    validation_signals: { github: true, media_coverage: true },
    source_count: 7,
    weekly_growth_rate: 6.0,
    monthly_growth_rate: 25.0,
    github_stars: 28000,
  },
  {
    slug: 'augment-code',
    name: 'Augment Code',
    name_en: 'Augment Code',
    name_zh: 'Augment Code',
    description_en: 'AI coding assistant with project-wide context awareness and agentic capabilities.',
    description_zh: '具有全项目上下文感知和智能体能力的 AI 编程助手。',
    website_url: 'https://augmentcode.com',
    category: 'AI Coding',
    subcategory: 'Code Assistant',
    tags: ['ai-coding', 'context-aware', 'developer-tools'],
    tech_stack: ['Python', 'TypeScript'],
    pricing_model: 'paid',
    pricing_url: 'https://augmentcode.com/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series B',
    founder_info: 'Niket Patel, Arvind Jain',
    launch_date: '2024-01-01',
    confidence_score: 82,
    confidence_level: 'medium',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 5,
    weekly_growth_rate: 3.0,
    monthly_growth_rate: 12.0,
  },
  {
    slug: 'boto',
    name: 'Bolt.new',
    name_en: 'Bolt.new',
    name_zh: 'Bolt.new',
    description_en: 'AI-powered web app builder by StackBlitz — prompt to full-stack app in browser.',
    description_zh: 'StackBlitz 推出的 AI Web 应用构建器，从提示到全栈应用。',
    website_url: 'https://bolt.new',
    category: 'AI Coding',
    subcategory: 'App Builder',
    tags: ['web-development', 'ai-builder', 'fullstack', 'stackblitz'],
    tech_stack: ['TypeScript', 'WebContainers', 'React'],
    pricing_model: 'freemium',
    pricing_url: 'https://bolt.new/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series B (StackBlitz)',
    founder_info: 'StackBlitz / Eric Simons',
    launch_date: '2024-08-01',
    confidence_score: 88,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 8,
    weekly_growth_rate: 2.2,
    monthly_growth_rate: 9.0,
  },

  // ─── AI Image Generation (19-27) ───
  {
    slug: 'midjourney',
    name: 'Midjourney',
    name_en: 'Midjourney',
    name_zh: 'Midjourney',
    description_en: 'AI image generation platform known for high-quality artistic images via Discord and web.',
    description_zh: '以高质量艺术性图像著称的 AI 图像生成平台。',
    website_url: 'https://midjourney.com',
    category: 'AI Image',
    subcategory: 'Image Generation',
    tags: ['image-generation', 'art', 'discord-bot', 'creative'],
    tech_stack: ['Python', 'PyTorch', 'Diffusion'],
    pricing_model: 'paid',
    pricing_url: 'https://midjourney.com/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Self-funded',
    founder_info: 'David Holz',
    launch_date: '2022-07-12',
    confidence_score: 96,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 12,
    weekly_growth_rate: 1.2,
    monthly_growth_rate: 5.0,
  },
  {
    slug: 'dall-e',
    name: 'DALL·E',
    name_en: 'DALL·E',
    name_zh: 'DALL·E',
    description_en: 'OpenAI\'s text-to-image model, integrated into ChatGPT and available via API.',
    description_zh: 'OpenAI 的文生图模型，已集成至 ChatGPT 并提供 API。',
    website_url: 'https://openai.com/index/dall-e',
    category: 'AI Image',
    subcategory: 'Image Generation',
    tags: ['image-generation', 'text-to-image', 'openai'],
    tech_stack: ['Python', 'PyTorch', 'Diffusion'],
    pricing_model: 'paid',
    availability_status: 'active',
    commercialization_status: 'Commercial (OpenAI API)',
    funding_stage: 'Internal (OpenAI)',
    founder_info: 'OpenAI',
    launch_date: '2021-01-05',
    confidence_score: 95,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 10,
    weekly_growth_rate: 0.8,
    monthly_growth_rate: 3.5,
  },
  {
    slug: 'stable-diffusion',
    name: 'Stable Diffusion',
    name_en: 'Stable Diffusion',
    name_zh: 'Stable Diffusion',
    description_en: 'Open-source text-to-image model by Stability AI, powering the ecosystem of SD tools.',
    description_zh: 'Stability AI 推出的开源文生图模型，驱动了整个 SD 工具生态。',
    website_url: 'https://stability.ai',
    github_url: 'https://github.com/Stability-AI/stablediffusion',
    category: 'AI Image',
    subcategory: 'Image Generation',
    tags: ['open-source', 'image-generation', 'diffusion', 'text-to-image'],
    tech_stack: ['Python', 'PyTorch', 'Diffusion'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source + Commercial API',
    funding_stage: 'Series (bankruptcy restructured)',
    founder_info: 'Stability AI / Emad Mostaque',
    launch_date: '2022-08-22',
    confidence_score: 93,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 11,
    weekly_growth_rate: 1.0,
    monthly_growth_rate: 4.0,
    github_stars: 45000,
  },
  {
    slug: 'flux',
    name: 'FLUX',
    name_en: 'FLUX',
    name_zh: 'FLUX',
    description_en: 'Open-source image generation model by Black Forest Labs, known for high quality and text rendering.',
    description_zh: 'Black Forest Labs 推出的开源图像生成模型，以高质量和文字渲染能力著称。',
    website_url: 'https://blackforestlabs.ai',
    github_url: 'https://github.com/black-forest-labs/flux',
    category: 'AI Image',
    subcategory: 'Image Generation',
    tags: ['open-source', 'image-generation', 'text-rendering'],
    tech_stack: ['Python', 'PyTorch', 'Diffusion'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source + API',
    funding_stage: 'Seed',
    founder_info: 'Robin Rombach, Patrick Esser (ex-Stability AI)',
    launch_date: '2024-08-01',
    confidence_score: 90,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 8,
    weekly_growth_rate: 4.0,
    monthly_growth_rate: 16.0,
    github_stars: 25000,
  },
  {
    slug: 'ideogram',
    name: 'Ideogram',
    name_en: 'Ideogram',
    name_zh: 'Ideogram',
    description_en: 'AI image generator with excellent typography and design capabilities.',
    description_zh: '具有优秀文字排版和设计能力的 AI 图像生成器。',
    website_url: 'https://ideogram.ai',
    category: 'AI Image',
    subcategory: 'Image Generation',
    tags: ['image-generation', 'typography', 'design'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'freemium',
    pricing_url: 'https://ideogram.ai/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series B ($450M valuation)',
    founder_info: 'Ex-Google Brain researchers',
    launch_date: '2023-08-01',
    confidence_score: 85,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 6,
    weekly_growth_rate: 2.0,
    monthly_growth_rate: 8.0,
  },
  {
    slug: 'comfyui',
    name: 'ComfyUI',
    name_en: 'ComfyUI',
    name_zh: 'ComfyUI',
    description_en: 'Node-based GUI for Stable Diffusion and other diffusion models, highly customizable.',
    description_zh: '基于节点的 Stable Diffusion 图形界面，高度可定制。',
    github_url: 'https://github.com/comfyanonymous/ComfyUI',
    category: 'AI Image',
    subcategory: 'Image Tools',
    tags: ['open-source', 'gui', 'stable-diffusion', 'node-based'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source',
    funding_stage: 'Community',
    founder_info: 'comfyanonymous',
    launch_date: '2023-01-15',
    confidence_score: 91,
    confidence_level: 'high',
    validation_signals: { github: true, media_coverage: true },
    source_count: 9,
    weekly_growth_rate: 3.5,
    monthly_growth_rate: 14.0,
    github_stars: 58000,
  },
  {
    slug: 'recraft',
    name: 'Recraft',
    name_en: 'Recraft',
    name_zh: 'Recraft',
    description_en: 'AI design tool for generating vector graphics, icons, and brand-consistent illustrations.',
    description_zh: '用于生成矢量图形、图标和品牌一致插画的 AI 设计工具。',
    website_url: 'https://recraft.ai',
    category: 'AI Image',
    subcategory: 'Design Tool',
    tags: ['vector', 'design', 'brand-consistency', 'illustration'],
    tech_stack: ['Python', 'React'],
    pricing_model: 'freemium',
    pricing_url: 'https://recraft.ai/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Seed',
    founder_info: 'Recraft OÜ',
    launch_date: '2023-05-01',
    confidence_score: 80,
    confidence_level: 'medium',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 5,
    weekly_growth_rate: 2.5,
    monthly_growth_rate: 10.0,
  },
  {
    slug: 'kling',
    name: '可灵',
    name_en: 'Kling AI',
    name_zh: '可灵',
    description_en: 'Kuaishou\'s AI video generation platform, supports image-to-video and text-to-video.',
    description_zh: '快手推出的 AI 视频生成平台，支持图生视频和文生视频。',
    website_url: 'https://klingai.com',
    category: 'AI Video',
    subcategory: 'Video Generation',
    tags: ['video-generation', 'chinese-ai', 'kuaishou'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'freemium',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Internal (Kuaishou)',
    founder_info: 'Kuaishou / 快手',
    launch_date: '2024-06-01',
    confidence_score: 88,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 7,
    weekly_growth_rate: 4.0,
    monthly_growth_rate: 16.0,
  },
  {
    slug: 'nano-banana-pro',
    name: 'Nano Banana Pro',
    name_en: 'Nano Banana Pro',
    name_zh: 'Nano Banana Pro',
    description_en: 'Emerging AI image generation tool known for fast inference and stylized outputs.',
    description_zh: '新兴 AI 图像生成工具，以快速推理和风格化输出著称。',
    website_url: 'https://nanobanana.pro',
    category: 'AI Image',
    subcategory: 'Image Generation',
    tags: ['image-generation', 'emerging', 'stylized'],
    tech_stack: ['Python'],
    pricing_model: 'freemium',
    availability_status: 'active',
    commercialization_status: 'Early Commercial',
    founder_info: 'Independent Team',
    launch_date: '2024-11-01',
    confidence_score: 55,
    confidence_level: 'medium',
    validation_signals: { official_website: true },
    source_count: 3,
    weekly_growth_rate: 8.0,
    monthly_growth_rate: 30.0,
  },

  // ─── AI Video Generation (28-32) ───
  {
    slug: 'runway',
    name: 'Runway',
    name_en: 'Runway',
    name_zh: 'Runway',
    description_en: 'AI creative tools for video generation, editing, and post-production (Gen-3 Alpha).',
    description_zh: 'AI 创意工具平台，提供视频生成、编辑和后期制作能力。',
    website_url: 'https://runwayml.com',
    category: 'AI Video',
    subcategory: 'Video Generation',
    tags: ['video-generation', 'creative-tools', 'gen3'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'freemium',
    pricing_url: 'https://runwayml.com/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series D (~$1.5B valuation)',
    founder_info: 'Cristóbal Valenzuela, Anastasis Germanidis',
    launch_date: '2021-06-01',
    confidence_score: 93,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 10,
    weekly_growth_rate: 2.0,
    monthly_growth_rate: 8.0,
  },
  {
    slug: 'pika',
    name: 'Pika',
    name_en: 'Pika',
    name_zh: 'Pika',
    description_en: 'AI video generation platform with cinematic quality and lip-sync features.',
    description_zh: '具有电影级质量和唇形同步功能的 AI 视频生成平台。',
    website_url: 'https://pika.art',
    category: 'AI Video',
    subcategory: 'Video Generation',
    tags: ['video-generation', 'lip-sync', 'cinematic'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'freemium',
    pricing_url: 'https://pika.art/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series A',
    founder_info: 'Stanford researchers',
    launch_date: '2023-11-01',
    confidence_score: 87,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 7,
    weekly_growth_rate: 2.5,
    monthly_growth_rate: 10.0,
  },
  {
    slug: 'veo',
    name: 'Google Veo',
    name_en: 'Google Veo',
    name_zh: 'Google Veo',
    description_en: 'Google\'s text-to-video model generating 1080p cinematic clips, available via VideoFX.',
    description_zh: 'Google 的文生视频模型，可生成 1080p 电影级片段。',
    website_url: 'https://deepmind.google/technologies/veo',
    category: 'AI Video',
    subcategory: 'Video Generation',
    tags: ['video-generation', 'google', '1080p'],
    tech_stack: ['Python', 'TensorFlow'],
    pricing_model: 'freemium',
    availability_status: 'active',
    commercialization_status: 'Commercial (Google)',
    funding_stage: 'Internal (Google)',
    founder_info: 'Google DeepMind',
    launch_date: '2024-05-01',
    confidence_score: 90,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 8,
    weekly_growth_rate: 1.5,
    monthly_growth_rate: 6.0,
  },
  {
    slug: 'sora',
    name: 'Sora',
    name_en: 'Sora',
    name_zh: 'Sora',
    description_en: 'OpenAI\'s text-to-video model capable of generating up to 20-second clips.',
    description_zh: 'OpenAI 的文生视频模型，可生成长达 20 秒的视频片段。',
    website_url: 'https://openai.com/sora',
    category: 'AI Video',
    subcategory: 'Video Generation',
    tags: ['video-generation', 'openai', 'text-to-video'],
    tech_stack: ['Python', 'PyTorch', 'Diffusion Transformers'],
    pricing_model: 'paid',
    availability_status: 'active',
    commercialization_status: 'Commercial (OpenAI)',
    funding_stage: 'Internal (OpenAI)',
    founder_info: 'OpenAI',
    launch_date: '2024-02-15',
    confidence_score: 94,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 10,
    weekly_growth_rate: 1.8,
    monthly_growth_rate: 7.0,
  },
  {
    slug: 'hailuo',
    name: '海螺AI',
    name_en: 'Hailuo AI',
    name_zh: '海螺AI',
    description_en: 'MiniMax\'s AI video generation platform with high-quality Chinese video outputs.',
    description_zh: 'MiniMax 推出的 AI 视频生成平台，以高质量中文视频输出著称。',
    website_url: 'https://hailuoai.com',
    category: 'AI Video',
    subcategory: 'Video Generation',
    tags: ['video-generation', 'chinese-ai', 'minimax'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'freemium',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series B',
    founder_info: 'MiniMax / 稀宇科技',
    launch_date: '2024-07-01',
    confidence_score: 84,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 6,
    weekly_growth_rate: 3.0,
    monthly_growth_rate: 12.0,
  },

  // ─── AI Search & Knowledge (33-39) ───
  {
    slug: 'perplexity',
    name: 'Perplexity AI',
    name_en: 'Perplexity AI',
    name_zh: 'Perplexity AI',
    description_en: 'AI-powered answer engine that provides sourced, conversational search results.',
    description_zh: 'AI 驱动的答案引擎，提供有来源的对话式搜索结果。',
    website_url: 'https://perplexity.ai',
    category: 'AI Search',
    subcategory: 'Answer Engine',
    tags: ['search', 'answer-engine', 'conversational', 'sourced'],
    tech_stack: ['Python', 'TypeScript', 'React'],
    pricing_model: 'freemium',
    pricing_url: 'https://perplexity.ai/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series D ($9B+ valuation)',
    founder_info: 'Aravind Srinivas, Denis Yarats, Johnny Ho, Andy Konwinski',
    launch_date: '2022-08-01',
    confidence_score: 95,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 12,
    weekly_growth_rate: 3.0,
    monthly_growth_rate: 12.0,
  },
  {
    slug: 'secret',
    name: '秘塔',
    name_en: 'Metaso',
    name_zh: '秘塔',
    description_en: 'Chinese AI search engine providing comprehensive search with AI-generated summaries.',
    description_zh: '中国 AI 搜索引擎，提供全面的搜索和 AI 生成的摘要。',
    website_url: 'https://metaso.cn',
    category: 'AI Search',
    subcategory: 'Search Engine',
    tags: ['chinese-ai', 'search', 'ai-summary'],
    tech_stack: ['Python'],
    pricing_model: 'freemium',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series A',
    founder_info: '秘塔科技',
    launch_date: '2023-09-01',
    confidence_score: 82,
    confidence_level: 'medium',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 5,
    weekly_growth_rate: 2.0,
    monthly_growth_rate: 8.0,
  },
  {
    slug: 'kimi-search',
    name: 'Kimi Search',
    name_en: 'Kimi Search',
    name_zh: 'Kimi 搜索',
    description_en: 'Moonshot AI\'s search feature within Kimi assistant, with deep page reading.',
    description_zh: '月之暗面 Kimi 助手内的搜索功能，支持深度页面阅读。',
    website_url: 'https://kimi.moonshot.cn',
    category: 'AI Search',
    subcategory: 'Search',
    tags: ['chinese-ai', 'search', 'deep-reading'],
    tech_stack: ['Python'],
    pricing_model: 'free',
    availability_status: 'active',
    commercialization_status: 'Free feature',
    funding_stage: 'See Kimi',
    founder_info: 'Moonshot AI',
    launch_date: '2024-08-01',
    confidence_score: 80,
    confidence_level: 'medium',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 4,
    weekly_growth_rate: 1.5,
    monthly_growth_rate: 6.0,
  },
  {
    slug: 'notebooklm',
    name: 'NotebookLM',
    name_en: 'NotebookLM',
    name_zh: 'NotebookLM',
    description_en: 'Google\'s AI research assistant that creates podcast-style audio overviews from your documents.',
    description_zh: 'Google 的 AI 研究助手，可从文档生成播客风格的音频摘要。',
    website_url: 'https://notebooklm.google',
    category: 'AI Search',
    subcategory: 'Research Assistant',
    tags: ['research', 'google', 'audio-overview', 'documents'],
    tech_stack: ['Python', 'TensorFlow'],
    pricing_model: 'free',
    availability_status: 'active',
    commercialization_status: 'Free (Google)',
    funding_stage: 'Internal (Google)',
    founder_info: 'Google',
    launch_date: '2024-05-01',
    confidence_score: 90,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 8,
    weekly_growth_rate: 3.0,
    monthly_growth_rate: 12.0,
  },
  {
    slug: 'you-search',
    name: 'You.com',
    name_en: 'You.com',
    description_en: 'AI-powered search engine with customizable AI agents and ad-free results.',
    website_url: 'https://you.com',
    category: 'AI Search',
    subcategory: 'Search Engine',
    tags: ['search', 'ai-agents', 'ad-free'],
    tech_stack: ['Python', 'React'],
    pricing_model: 'freemium',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series B',
    founder_info: 'Richard Socher',
    launch_date: '2021-09-01',
    confidence_score: 83,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 5,
    weekly_growth_rate: 1.0,
    monthly_growth_rate: 4.0,
  },
  {
    slug: 'chatglm',
    name: '智谱清言',
    name_en: 'ChatGLM',
    name_zh: '智谱清言',
    description_en: 'Zhipu AI\'s conversational platform with GLM models, popular in China.',
    description_zh: '智谱 AI 的对话平台，基于 GLM 模型，在中国广受欢迎。',
    website_url: 'https://chatglm.cn',
    github_url: 'https://github.com/THUDM/ChatGLM-6B',
    category: 'LLM',
    subcategory: 'Chatbot',
    tags: ['chinese-llm', 'open-source', 'glm'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'freemium',
    availability_status: 'active',
    commercialization_status: 'Commercial + Open Source',
    funding_stage: 'Series C',
    founder_info: '智谱 AI / 唐杰',
    launch_date: '2023-03-01',
    confidence_score: 90,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 8,
    weekly_growth_rate: 1.5,
    monthly_growth_rate: 6.0,
    github_stars: 16000,
  },
  {
    slug: 'groq',
    name: 'Groq',
    name_en: 'Groq',
    description_en: 'Ultra-fast AI inference company with custom LPU hardware, powering instant chat and API.',
    website_url: 'https://groq.com',
    category: 'AI Infra',
    subcategory: 'Inference',
    tags: ['inference', 'hardware', 'low-latency', 'lpu'],
    tech_stack: ['C', 'Python', 'Custom Hardware'],
    pricing_model: 'freemium',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series D ($7B+ valuation)',
    founder_info: 'Jonathan Ross',
    launch_date: '2023-01-01',
    confidence_score: 88,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 8,
    weekly_growth_rate: 2.5,
    monthly_growth_rate: 10.0,
  },

  // ─── AI Productivity (40-46) ───
  {
    slug: 'notion-ai',
    name: 'Notion AI',
    name_en: 'Notion AI',
    description_en: 'AI writing and productivity assistant built into Notion workspace.',
    website_url: 'https://notion.so/product/ai',
    category: 'AI Productivity',
    subcategory: 'Writing Assistant',
    tags: ['writing', 'workspace', 'productivity', 'notion'],
    tech_stack: ['TypeScript', 'React', 'OpenAI API'],
    pricing_model: 'paid',
    pricing_url: 'https://notion.so/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial (Notion Labs)',
    funding_stage: 'Series C',
    founder_info: 'Notion Labs / Ivan Zhao',
    launch_date: '2023-02-22',
    confidence_score: 94,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 10,
    weekly_growth_rate: 1.0,
    monthly_growth_rate: 4.0,
  },
  {
    slug: 'gamma',
    name: 'Gamma',
    name_en: 'Gamma',
    description_en: 'AI-powered presentation and document creation tool — generate slides from text prompts.',
    website_url: 'https://gamma.app',
    category: 'AI Productivity',
    subcategory: 'Presentation',
    tags: ['presentations', 'slides', 'ai-generation'],
    tech_stack: ['TypeScript', 'React'],
    pricing_model: 'freemium',
    pricing_url: 'https://gamma.app/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series A',
    founder_info: 'Gamma Technologies',
    launch_date: '2023-04-01',
    confidence_score: 86,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 6,
    weekly_growth_rate: 3.0,
    monthly_growth_rate: 12.0,
  },
  {
    slug: 'tome',
    name: 'Tome',
    name_en: 'Tome',
    description_en: 'AI-powered storytelling and presentation platform with generative media.',
    website_url: 'https://tome.app',
    category: 'AI Productivity',
    subcategory: 'Presentation',
    tags: ['presentations', 'storytelling', 'generative-media'],
    tech_stack: ['TypeScript', 'React'],
    pricing_model: 'freemium',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series B',
    founder_info: 'Henrik Werdelin, Keith Peiris',
    launch_date: '2022-09-01',
    confidence_score: 83,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 5,
    weekly_growth_rate: 1.0,
    monthly_growth_rate: 4.0,
  },
  {
    slug: 'ludo-ai',
    name: 'Ludo AI',
    name_en: 'Ludo AI',
    description_en: 'AI research and brainstorming tool for creative professionals and game developers.',
    website_url: 'https://ludo.ai',
    category: 'AI Productivity',
    subcategory: 'Research',
    tags: ['research', 'brainstorming', 'game-dev'],
    tech_stack: ['Python'],
    pricing_model: 'freemium',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    founder_info: 'Ludo AI Team',
    launch_date: '2023-06-01',
    confidence_score: 65,
    confidence_level: 'medium',
    validation_signals: { official_website: true },
    source_count: 3,
    weekly_growth_rate: 1.5,
    monthly_growth_rate: 6.0,
  },
  {
    slug: 'beautiful-ai',
    name: 'Beautiful.ai',
    name_en: 'Beautiful.ai',
    description_en: 'AI-powered slide design tool with smart templates and auto-layout.',
    website_url: 'https://beautiful.ai',
    category: 'AI Productivity',
    subcategory: 'Presentation',
    tags: ['slides', 'design', 'auto-layout'],
    tech_stack: ['TypeScript', 'React'],
    pricing_model: 'paid',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Acquired',
    founder_info: 'Beautiful.ai Inc.',
    launch_date: '2015-01-01',
    confidence_score: 82,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 5,
    weekly_growth_rate: 0.5,
    monthly_growth_rate: 2.0,
  },
  {
    slug: 'fireflies',
    name: 'Fireflies.ai',
    name_en: 'Fireflies.ai',
    description_en: 'AI meeting assistant that transcribes, summarizes, and analyzes meetings automatically.',
    website_url: 'https://fireflies.ai',
    category: 'AI Productivity',
    subcategory: 'Meeting Assistant',
    tags: ['meetings', 'transcription', 'summaries'],
    tech_stack: ['Python', 'React', 'NLP'],
    pricing_model: 'freemium',
    pricing_url: 'https://fireflies.ai/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series A',
    founder_info: 'Fireflies AI Team',
    launch_date: '2020-01-01',
    confidence_score: 85,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 6,
    weekly_growth_rate: 1.5,
    monthly_growth_rate: 6.0,
  },
  {
    slug: 'suno',
    name: 'Suno',
    name_en: 'Suno',
    description_en: 'AI music generation platform — create full songs from text prompts with vocals.',
    website_url: 'https://suno.com',
    github_url: 'https://github.com/suno-ai',
    category: 'AI Audio',
    subcategory: 'Music Generation',
    tags: ['music', 'audio-generation', 'vocals', 'creative'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'freemium',
    pricing_url: 'https://suno.com/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series B',
    founder_info: 'Mikey Shulman',
    launch_date: '2023-01-01',
    confidence_score: 90,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 8,
    weekly_growth_rate: 3.0,
    monthly_growth_rate: 12.0,
  },

  // ─── AI Voice & Audio (47-51) ───
  {
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    name_en: 'ElevenLabs',
    description_en: 'AI voice synthesis platform with realistic text-to-speech and voice cloning.',
    website_url: 'https://elevenlabs.io',
    category: 'AI Audio',
    subcategory: 'Voice Synthesis',
    tags: ['voice', 'text-to-speech', 'voice-cloning'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'freemium',
    pricing_url: 'https://elevenlabs.io/pricing',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Series C (~$3B valuation)',
    founder_info: 'Piotr Dabkowski, Mati Staniszewski',
    launch_date: '2022-09-01',
    confidence_score: 93,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 10,
    weekly_growth_rate: 2.5,
    monthly_growth_rate: 10.0,
  },
  {
    slug: 'openvoice',
    name: 'OpenVoice',
    name_en: 'OpenVoice',
    description_en: 'Open-source instant voice cloning technology by MyShell, highly accurate and lightweight.',
    github_url: 'https://github.com/myshell-ai/OpenVoice',
    category: 'AI Audio',
    subcategory: 'Voice Cloning',
    tags: ['open-source', 'voice-cloning', 'myshell'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source',
    funding_stage: 'Community',
    founder_info: 'MyShell AI',
    launch_date: '2023-12-01',
    confidence_score: 84,
    confidence_level: 'high',
    validation_signals: { github: true, media_coverage: true },
    source_count: 5,
    weekly_growth_rate: 2.0,
    monthly_growth_rate: 8.0,
    github_stars: 8000,
  },
  {
    slug: 'cosyvoice',
    name: 'CosyVoice',
    name_en: 'CosyVoice',
    name_zh: 'CosyVoice',
    description_en: 'Open-source multilingual TTS model by Alibaba DAMO Academy.',
    description_zh: '阿里达摩院推出的开源多语言 TTS 模型。',
    github_url: 'https://github.com/FunAudioLLM/CosyVoice',
    category: 'AI Audio',
    subcategory: 'Text-to-Speech',
    tags: ['open-source', 'tts', 'multilingual', 'alibaba'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source',
    funding_stage: 'Internal (Alibaba)',
    founder_info: '阿里达摩院',
    launch_date: '2024-01-01',
    confidence_score: 82,
    confidence_level: 'high',
    validation_signals: { github: true, media_coverage: true },
    source_count: 4,
    weekly_growth_rate: 2.5,
    monthly_growth_rate: 10.0,
    github_stars: 9000,
  },
  {
    slug: 'fish-audio',
    name: 'Fish Audio',
    name_en: 'Fish Audio',
    name_zh: 'Fish Audio',
    description_en: 'AI voice generation platform with multi-language support and API access.',
    description_zh: '支持多语言和 API 访问的 AI 语音生成平台。',
    website_url: 'https://fish.audio',
    category: 'AI Audio',
    subcategory: 'Voice Generation',
    tags: ['voice', 'api', 'multilingual'],
    tech_stack: ['Python', 'PyTorch'],
    pricing_model: 'freemium',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Seed',
    founder_info: 'Fish Audio Team',
    launch_date: '2024-03-01',
    confidence_score: 72,
    confidence_level: 'medium',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 3,
    weekly_growth_rate: 4.0,
    monthly_growth_rate: 16.0,
  },
  {
    slug: 'minimax-speech',
    name: 'MiniMax 语音',
    name_en: 'MiniMax Speech',
    name_zh: 'MiniMax 语音',
    description_en: 'MiniMax\'s speech synthesis API with highly expressive and natural voice outputs.',
    description_zh: 'MiniMax 的语音合成 API，输出高度自然流畅。',
    website_url: 'https://platform.minimaxi.com',
    category: 'AI Audio',
    subcategory: 'Speech Synthesis',
    tags: ['chinese-ai', 'speech', 'api'],
    tech_stack: ['Python'],
    pricing_model: 'paid',
    availability_status: 'active',
    commercialization_status: 'Commercial API',
    funding_stage: 'Series B',
    founder_info: 'MiniMax',
    launch_date: '2023-06-01',
    confidence_score: 78,
    confidence_level: 'medium',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 4,
    weekly_growth_rate: 2.0,
    monthly_growth_rate: 8.0,
  },

  // ─── AI Agents & Automation (52-58) ───
  {
    slug: 'dify',
    name: 'Dify',
    name_en: 'Dify',
    name_zh: 'Dify',
    description_en: 'Open-source LLM app development platform with visual workflow builder.',
    description_zh: '开源 LLM 应用开发平台，提供可视化工作流构建器。',
    website_url: 'https://dify.ai',
    github_url: 'https://github.com/langgenius/dify',
    category: 'AI Agents',
    subcategory: 'LLM App Platform',
    tags: ['open-source', 'llm-apps', 'workflow', 'low-code'],
    tech_stack: ['Python', 'TypeScript', 'Next.js', 'Docker'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source + Cloud',
    funding_stage: 'Series A',
    founder_info: 'Dify Team',
    launch_date: '2023-04-01',
    confidence_score: 90,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 9,
    weekly_growth_rate: 4.0,
    monthly_growth_rate: 16.0,
    github_stars: 55000,
  },
  {
    slug: 'langchain',
    name: 'LangChain',
    name_en: 'LangChain',
    description_en: 'Open-source framework for building applications powered by large language models.',
    github_url: 'https://github.com/langchain-ai/langchain',
    website_url: 'https://langchain.com',
    category: 'AI Agents',
    subcategory: 'Framework',
    tags: ['open-source', 'framework', 'llm-apps', 'python'],
    tech_stack: ['Python', 'TypeScript'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source + LangSmith',
    funding_stage: 'Series B',
    founder_info: 'Harrison Chase',
    launch_date: '2022-10-01',
    confidence_score: 96,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 13,
    weekly_growth_rate: 1.0,
    monthly_growth_rate: 4.0,
    github_stars: 105000,
  },
  {
    slug: 'crewai',
    name: 'CrewAI',
    name_en: 'CrewAI',
    description_en: 'Framework for orchestrating role-playing AI agents working together on tasks.',
    github_url: 'https://github.com/crewAIInc/crewAI',
    website_url: 'https://crewai.com',
    category: 'AI Agents',
    subcategory: 'Agent Framework',
    tags: ['open-source', 'multi-agent', 'orchestration'],
    tech_stack: ['Python'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source + Enterprise',
    funding_stage: 'Seed',
    founder_info: 'João Moura',
    launch_date: '2023-10-01',
    confidence_score: 87,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 8,
    weekly_growth_rate: 5.0,
    monthly_growth_rate: 20.0,
    github_stars: 24000,
  },
  {
    slug: 'open-webui',
    name: 'Open WebUI',
    name_en: 'Open WebUI',
    description_en: 'Self-hosted web UI for Ollama and OpenAI-compatible APIs, feature-rich and community-driven.',
    github_url: 'https://github.com/open-webui/open-webui',
    website_url: 'https://openwebui.com',
    category: 'AI Agents',
    subcategory: 'Web UI',
    tags: ['open-source', 'self-hosted', 'ollama', 'web-ui'],
    tech_stack: ['Python', 'Svelte'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source',
    funding_stage: 'Community',
    founder_info: 'Community',
    launch_date: '2023-06-01',
    confidence_score: 88,
    confidence_level: 'high',
    validation_signals: { github: true, media_coverage: true },
    source_count: 7,
    weekly_growth_rate: 3.5,
    monthly_growth_rate: 14.0,
    github_stars: 48000,
  },
  {
    slug: 'coze',
    name: '扣子',
    name_en: 'Coze',
    name_zh: '扣子',
    description_en: 'ByteDance\'s AI bot development platform with no-code workflow builder and plugin ecosystem.',
    description_zh: '字节跳动的 AI 机器人开发平台，提供无代码工作流构建器和插件生态。',
    website_url: 'https://coze.cn',
    category: 'AI Agents',
    subcategory: 'Bot Platform',
    tags: ['chinese-ai', 'no-code', 'bot-platform', 'bytedance'],
    tech_stack: ['Go', 'TypeScript'],
    pricing_model: 'freemium',
    availability_status: 'active',
    commercialization_status: 'Commercial',
    funding_stage: 'Internal (ByteDance)',
    founder_info: '字节跳动',
    launch_date: '2023-08-01',
    confidence_score: 88,
    confidence_level: 'high',
    validation_signals: { official_website: true, media_coverage: true },
    source_count: 7,
    weekly_growth_rate: 2.0,
    monthly_growth_rate: 8.0,
  },
  {
    slug: 'n8n',
    name: 'n8n',
    name_en: 'n8n',
    description_en: 'Fair-code workflow automation platform with AI/LLM integration nodes.',
    github_url: 'https://github.com/n8n-io/n8n',
    website_url: 'https://n8n.io',
    category: 'AI Agents',
    subcategory: 'Workflow Automation',
    tags: ['open-source', 'automation', 'workflow', 'ai-integration'],
    tech_stack: ['TypeScript', 'Node.js', 'Vue'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Fair-code + Cloud',
    funding_stage: 'Series B',
    founder_info: 'Jan Oberhauser',
    launch_date: '2019-01-01',
    confidence_score: 92,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 10,
    weekly_growth_rate: 3.0,
    monthly_growth_rate: 12.0,
    github_stars: 62000,
  },
  {
    slug: 'ragflow',
    name: 'RAGFlow',
    name_en: 'RAGFlow',
    name_zh: 'RAGFlow',
    description_en: 'Open-source RAG engine with deep document understanding and visual pipeline builder.',
    description_zh: '开源 RAG 引擎，具有深度文档理解能力和可视化管线构建器。',
    github_url: 'https://github.com/infiniflow/ragflow',
    website_url: 'https://ragflow.io',
    category: 'AI Agents',
    subcategory: 'RAG Engine',
    tags: ['open-source', 'rag', 'document-understanding'],
    tech_stack: ['Python', 'Elasticsearch', 'Milvus'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source',
    funding_stage: 'Series (InfiniFlow)',
    founder_info: 'InfiniFlow',
    launch_date: '2024-01-01',
    confidence_score: 83,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 6,
    weekly_growth_rate: 4.5,
    monthly_growth_rate: 18.0,
    github_stars: 35000,
  },

  // ─── AI Infra / DevTools (59-63) ───
  {
    slug: 'ollama',
    name: 'Ollama',
    name_en: 'Ollama',
    description_en: 'Run LLMs locally with a simple CLI — Llama, Mistral, Phi and more.',
    github_url: 'https://github.com/ollama/ollama',
    website_url: 'https://ollama.com',
    category: 'AI Infra',
    subcategory: 'Local LLM Runtime',
    tags: ['open-source', 'local-llm', 'cli', 'self-hosted'],
    tech_stack: ['Go', 'C', 'CUDA'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source + Enterprise',
    funding_stage: 'Series A',
    founder_info: 'Jeffrey Morgan',
    launch_date: '2023-04-01',
    confidence_score: 95,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 12,
    weekly_growth_rate: 3.0,
    monthly_growth_rate: 12.0,
    github_stars: 110000,
  },
  {
    slug: 'vllm',
    name: 'vLLM',
    name_en: 'vLLM',
    description_en: 'High-throughput and memory-efficient LLM inference engine with PagedAttention.',
    github_url: 'https://github.com/vllm-project/vllm',
    website_url: 'https://docs.vllm.ai',
    category: 'AI Infra',
    subcategory: 'Inference Engine',
    tags: ['open-source', 'inference', 'gpu', 'pagedattention'],
    tech_stack: ['Python', 'CUDA', 'C++'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source',
    funding_stage: 'Community (Berkeley)',
    founder_info: 'UC Berkeley SkyLab',
    launch_date: '2023-01-01',
    confidence_score: 94,
    confidence_level: 'high',
    validation_signals: { github: true, media_coverage: true },
    source_count: 11,
    weekly_growth_rate: 2.0,
    monthly_growth_rate: 8.0,
    github_stars: 48000,
  },
  {
    slug: 'lobe-chat',
    name: 'LobeChat',
    name_en: 'LobeChat',
    name_zh: 'LobeChat',
    description_en: 'Open-source, modern-design chat UI supporting multiple LLM providers.',
    description_zh: '开源、现代设计风格的聊天界面，支持多个 LLM 供应商。',
    github_url: 'https://github.com/lobehub/lobe-chat',
    website_url: 'https://lobechat.com',
    category: 'AI Infra',
    subcategory: 'Chat UI',
    tags: ['open-source', 'chat-ui', 'multi-provider', 'nextjs'],
    tech_stack: ['TypeScript', 'Next.js', 'React'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source',
    funding_stage: 'Community',
    founder_info: 'LobeHub',
    launch_date: '2023-06-01',
    confidence_score: 85,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 7,
    weekly_growth_rate: 1.5,
    monthly_growth_rate: 6.0,
    github_stars: 50000,
  },
  {
    slug: 'anything-llm',
    name: 'AnythingLLM',
    name_en: 'AnythingLLM',
    description_en: 'All-in-one desktop app to chat with your documents using local or cloud LLMs.',
    github_url: 'https://github.com/Mintplex-Labs/anything-llm',
    website_url: 'https://anythingllm.com',
    category: 'AI Infra',
    subcategory: 'Document Chat',
    tags: ['open-source', 'rag', 'document-chat', 'desktop'],
    tech_stack: ['JavaScript', 'React', 'Electron'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source + Enterprise',
    funding_stage: 'Seed',
    founder_info: 'Mintplex Labs',
    launch_date: '2023-05-01',
    confidence_score: 82,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 6,
    weekly_growth_rate: 1.0,
    monthly_growth_rate: 4.0,
    github_stars: 25000,
  },
  {
    slug: 'fastgpt',
    name: 'FastGPT',
    name_en: 'FastGPT',
    name_zh: 'FastGPT',
    description_en: 'Open-source knowledge base Q&A system with visual workflow builder and RAG support.',
    description_zh: '开源知识库问答系统，支持可视化工作流构建和 RAG。',
    github_url: 'https://github.com/labring/FastGPT',
    website_url: 'https://fastgpt.in',
    category: 'AI Agents',
    subcategory: 'Knowledge Base',
    tags: ['open-source', 'rag', 'knowledge-base', 'workflow'],
    tech_stack: ['TypeScript', 'Next.js', 'MongoDB'],
    pricing_model: 'open_source',
    availability_status: 'active',
    commercialization_status: 'Open Source + Cloud',
    funding_stage: 'Community',
    founder_info: 'FastGPT Team',
    launch_date: '2023-03-01',
    confidence_score: 84,
    confidence_level: 'high',
    validation_signals: { official_website: true, github: true, media_coverage: true },
    source_count: 6,
    weekly_growth_rate: 2.0,
    monthly_growth_rate: 8.0,
    github_stars: 32000,
  },
];

// ── generate SQL ─────────────────────────────────────────────────────
const columns = [
  'slug', 'name', 'name_en', 'name_zh',
  'description_en', 'description_zh',
  'website_url', 'github_url', 'logo_url',
  'category', 'subcategory',
  'tags', 'tech_stack',
  'pricing_model', 'pricing_url',
  'availability_status', 'commercialization_status', 'funding_stage', 'founder_info',
  'launch_date',
  'confidence_score', 'confidence_level',
  'validation_signals', 'source_count',
  'weekly_growth_rate', 'monthly_growth_rate',
  'github_stars',
];

function generateSQL(): string {
  const lines: string[] = [
    '-- AI Radar Seed Data',
    `-- Generated: ${new Date().toISOString()}`,
    `-- Total products: ${products.length}`,
    '',
    '-- Truncate existing data (safe for fresh seed)',
    'TRUNCATE TABLE products CASCADE;',
    '',
    '-- Insert products',
    'INSERT INTO products (' + columns.join(', ') + ') VALUES',
  ];

  const values = products.map((p, i) => {
    const vals = columns.map((c) => {
      const v = (p as Record<string, any>)[c];
      if (v === undefined || v === null) return 'NULL';
      if (Array.isArray(v)) return arr(v);
      if (typeof v === 'object') return obj(v);
      if (typeof v === 'number') return v.toString();
      return esc(v);
    });
    return `  (${vals.join(', ')})${i < products.length - 1 ? ',' : ';'}`;
  });

  lines.push(...values);
  lines.push('');
  lines.push('-- Reset sequences');
  lines.push(`-- Done. Inserted ${products.length} products.`);

  return lines.join('\n');
}

console.log(generateSQL());
