-- =====================================================================
-- AI Radar Phase E — Products Seed (40 L1 Mature Products)
-- File: supabase/seed-phase-e-products-40.sql
-- Author: 寇豆码 (Engineer)
-- Date: 2026-05-31
-- Related: T03 (A线-W1)
--
-- 说明:
--   现有 63 条 products 已覆盖 L1 成熟产品（含 ChatGPT/Claude/Cursor/Midjourney/Runway/Perplexity）。
--   本文件再追加 40 条新的 L1 成熟产品，覆盖全部 13 个分类，包括
--   4 个新分类（AI Education / Customer Service / Healthcare / Marketing）的新增产品。
--
-- 分类分布（13 个分类，40 条）:
--   LLM: 4 (Hunyuan, GLM-4, Doubao, Baichuan)
--   AI Image: 3 (Adobe Firefly, Leonardo, Playground)
--   AI Coding: 3 (Replit, Cody, Tabnine)
--   AI Agents: 3 (AutoGPT, Manus, Lindy)
--   AI Productivity: 3 (Grammarly, Otter.ai, Mem)
--   AI Audio: 3 (PlayHT, Resemble, AIVA)
--   AI Video: 3 (Luma Dream Machine, Synthesia, HeyGen)
--   AI Infra: 3 (Hugging Face, Replicate, Anyscale)
--   AI Search: 3 (Brave Search, Andi, Komo)
--   AI Education: 4 (Khanmigo, Duolingo Max, Speak, Quizlet Q-Chat)
--   AI Customer Service: 3 (Intercom Fin, Ada, Forethought)
--   AI Healthcare: 2 (Hippocratic AI, Glass Health)
--   AI Marketing: 3 (Jasper, Copy.ai, Mutiny)
--
-- 幂等策略:
--   INSERT ... ON CONFLICT (slug) DO UPDATE SET ... —— 重复执行安全
-- =====================================================================

INSERT INTO products (
  slug, name, name_en, name_zh,
  description_en, description_zh,
  website_url, github_url, logo_url,
  category, subcategory, tags, tech_stack,
  pricing_model, pricing_url, availability_status,
  commercialization_status, funding_stage, founder_info,
  launch_date, confidence_score, confidence_level,
  validation_signals, source_count,
  weekly_growth_rate, monthly_growth_rate, github_stars
) VALUES
  -- ===== LLM (4) =====
  ('hunyuan', 'Tencent Hunyuan', 'Tencent Hunyuan', '腾讯混元',
   'Tencent''s foundation model family (Hunyuan-Pro, Hunyuan-3D, Hunyuan-Vision).', '腾讯混元大模型系列，涵盖 Hunyuan-Pro / Hunyuan-3D / Hunyuan-Vision。',
   'https://hunyuan.tencent.com', 'https://github.com/Tencent/Hunyuan', NULL,
   'LLM', 'Foundation Model',
   ARRAY['chinese-llm','foundation-model','tencent','multimodal','3d'],
   ARRAY['Python','PyTorch','AngelPTM'],
   'freemium', 'https://cloud.tencent.com/product/hunyuan', 'active',
   'Commercial + Open Source', 'Internal (Tencent)',
   'Tencent / 腾讯', '2023-09-07', 92, 'high',
   '{"official_website":true,"github":true,"media_coverage":true}', 10, 1.5, 6.2, 4200),

  ('glm-4', 'Zhipu GLM-4', 'Zhipu GLM-4', '智谱 GLM-4',
   'Zhipu AI''s flagship LLM family (GLM-4 / GLM-4-Plus / GLM-Z1) with strong Chinese and English.', '智谱 AI 旗舰大模型系列（GLM-4 / GLM-4-Plus / GLM-Z1），中英文表现均衡。',
   'https://www.zhipuai.cn', 'https://github.com/THUDM/GLM-4', NULL,
   'LLM', 'Foundation Model',
   ARRAY['chinese-llm','open-source','foundation-model','zhipuai'],
   ARRAY['Python','PyTorch'],
   'freemium', 'https://open.bigmodel.cn/pricing', 'active',
   'Commercial + Open Source', 'Series (Alibaba/Huawei backed)',
   '唐杰 / 张鹏 (Zhipu AI)', '2024-01-16', 91, 'high',
   '{"official_website":true,"github":true,"media_coverage":true}', 9, 2.1, 8.5, 8500),

  ('doubao', 'ByteDance Doubao', 'ByteDance Doubao', '字节豆包',
   'ByteDance''s consumer-facing AI assistant powered by the Doubao Pro model family.', '字节跳动面向消费者的 AI 助手，搭载豆包 Pro 模型系列。',
   'https://www.doubao.com', NULL, NULL,
   'LLM', 'Chatbot',
   ARRAY['chinese-llm','chatbot','bytedance','consumer-ai'],
   ARRAY['Python','PyTorch','ByteDance-AML'],
   'freemium', NULL, 'active',
   'Commercial', 'Internal (ByteDance)',
   'ByteDance / 字节跳动', '2023-08-17', 89, 'high',
   '{"official_website":true,"media_coverage":true}', 7, 3.5, 14, NULL),

  ('baichuan', 'Baichuan Inc.', 'Baichuan Inc.', '百川智能',
   'Chinese foundation model company from Wang Xingfeng (former Sogou CEO), with Baichuan 2/3/4 family.', '王小川（前搜狗 CEO）创立的中文基础模型公司，发布百川 2/3/4 模型系列。',
   'https://www.baichuan-ai.com', 'https://github.com/baichuan-inc', NULL,
   'LLM', 'Foundation Model',
   ARRAY['chinese-llm','open-source','foundation-model','baichuan'],
   ARRAY['Python','PyTorch'],
   'freemium', 'https://platform.baichuan-ai.com/price', 'active',
   'Commercial + Open Source', 'Series A ($1B valuation)',
   '王小川 (Wang Xiaofeng)', '2023-06-15', 85, 'high',
   '{"official_website":true,"github":true,"media_coverage":true}', 6, 1.0, 4.0, 3200),

  -- ===== AI Image (3) =====
  ('adobe-firefly', 'Adobe Firefly', 'Adobe Firefly', 'Adobe Firefly',
   'Adobe''s commercial-safe image generation model integrated across Photoshop, Illustrator, and Express.', 'Adobe 商用安全图像生成模型，集成至 Photoshop、Illustrator 和 Express。',
   'https://firefly.adobe.com', NULL, NULL,
   'AI Image', 'Image Generation',
   ARRAY['image-generation','commercial-safe','adobe','creative-suite'],
   ARRAY['Python','PyTorch','Diffusion'],
   'paid', 'https://www.adobe.com/products/firefly.html', 'active',
   'Commercial (Adobe)', 'Internal (Adobe)',
   'Adobe Inc.', '2023-03-21', 93, 'high',
   '{"official_website":true,"github":false,"media_coverage":true}', 9, 1.0, 4.5, NULL),

  ('leonardo-ai', 'Leonardo.AI', 'Leonardo.AI', 'Leonardo.AI',
   'AI image and asset generation platform tailored for game, art, and creative production.', '面向游戏、艺术和创意生产的 AI 图像与素材生成平台。',
   'https://leonardo.ai', NULL, NULL,
   'AI Image', 'Image Generation',
   ARRAY['image-generation','game-assets','creative-tools','canvas'],
   ARRAY['Python','PyTorch','Diffusion'],
   'freemium', 'https://leonardo.ai/pricing', 'active',
   'Commercial', 'Series B',
   'JJ Fiasson, Jinni Wernick', '2022-11-01', 88, 'high',
   '{"official_website":true,"media_coverage":true}', 7, 2.8, 11, NULL),

  ('playground-ai', 'Playground AI', 'Playground AI', 'Playground AI',
   'Free online AI image generator with social canvas, supporting SDXL and DALL·E 3.', '免费的在线 AI 图像生成器，支持 SDXL 和 DALL·E 3，提供社交画布。',
   'https://playground.com', NULL, NULL,
   'AI Image', 'Image Generation',
   ARRAY['image-generation','free-tier','sdxl','social-canvas'],
   ARRAY['Python','PyTorch','Diffusion'],
   'freemium', 'https://playground.com/pricing', 'active',
   'Commercial', 'Series A',
   'Suhail Doshi', '2022-07-01', 82, 'medium',
   '{"official_website":true,"media_coverage":true}', 5, 0.6, 2.5, NULL),

  -- ===== AI Coding (3) =====
  ('replit', 'Replit Agent', 'Replit Agent', 'Replit Agent',
   'Replit''s AI agent that builds and deploys full apps from natural language in the browser.', 'Replit 的 AI 智能体，可在浏览器中通过自然语言构建并部署完整应用。',
   'https://replit.com', NULL, NULL,
   'AI Coding', 'App Builder',
   ARRAY['app-builder','ai-agent','cloud-ide','fullstack'],
   ARRAY['TypeScript','React','LLM','Firecracker'],
   'freemium', 'https://replit.com/pricing', 'active',
   'Commercial', 'Public (REPL)',
   'Amjad Masad', '2016-04-01', 91, 'high',
   '{"official_website":true,"media_coverage":true}', 9, 1.5, 6.5, NULL),

  ('cody', 'Sourcegraph Cody', 'Sourcegraph Cody', 'Sourcegraph Cody',
   'Sourcegraph''s AI coding assistant with full codebase context and code-graph awareness.', 'Sourcegraph 的 AI 编程助手，具备完整代码库上下文与代码图谱感知能力。',
   'https://sourcegraph.com/cody', 'https://github.com/sourcegraph/cody', NULL,
   'AI Coding', 'Code Assistant',
   ARRAY['code-completion','codebase-context','enterprise','code-search'],
   ARRAY['TypeScript','Go','LLM'],
   'freemium', 'https://sourcegraph.com/pricing', 'active',
   'Commercial', 'Series E',
   'Quinn Slack', '2023-04-12', 87, 'high',
   '{"official_website":true,"github":true,"media_coverage":true}', 7, 1.2, 5.0, 3600),

  ('tabnine', 'Tabnine', 'Tabnine', 'Tabnine',
   'Enterprise-focused AI code completion assistant supporting private models and on-prem deployment.', '面向企业的 AI 代码补全助手，支持私有模型与本地化部署。',
   'https://www.tabnine.com', NULL, NULL,
   'AI Coding', 'Code Completion',
   ARRAY['code-completion','enterprise','private-model','on-prem'],
   ARRAY['Java','Python','TypeScript'],
   'paid', 'https://www.tabnine.com/pricing', 'active',
   'Commercial', 'Series B (acquired by Atlassian rumors)',
   'Eran Yahav', '2018-12-01', 84, 'high',
   '{"official_website":true,"media_coverage":true}', 6, 0.5, 2.0, NULL),

  -- ===== AI Agents (3) =====
  ('autogpt', 'AutoGPT', 'AutoGPT', 'AutoGPT',
   'Open-source autonomous GPT-4 agent capable of chaining tasks to achieve goals.', '基于 GPT-4 的开源自主智能体，可链式执行任务以达成目标。',
   NULL, 'https://github.com/Significant-Gravitas/AutoGPT', NULL,
   'AI Agents', 'Autonomous Agent',
   ARRAY['open-source','autonomous-agent','gpt-4','task-planning'],
   ARRAY['Python','OpenAI API'],
   'open_source', NULL, 'active',
   'Open Source', 'Open Source',
   'Significant Gravitas', '2023-03-30', 90, 'high',
   '{"github":true,"media_coverage":true}', 8, 1.0, 4.0, 175000),

  ('manus', 'Manus AI', 'Manus AI', 'Manus AI',
   'Manus — general AI agent from Butterfly Effect, capable of autonomous task execution.', 'Manus —— 蝴蝶效应推出的通用 AI 智能体，可自主执行任务。',
   'https://manus.im', NULL, NULL,
   'AI Agents', 'Autonomous Agent',
   ARRAY['general-agent','autonomous','chinese-ai','task-execution'],
   ARRAY['Python','LLM'],
   'freemium', NULL, 'active',
   'Commercial', 'Seed (Hillhouse-backed)',
   '肖弘 (Xiao Hong)', '2025-03-06', 92, 'high',
   '{"official_website":true,"media_coverage":true}', 11, 8.0, 32, NULL),

  ('lindy', 'Lindy AI', 'Lindy AI', 'Lindy AI',
   'No-code platform for building personal AI agents that integrate with email, calendar, and CRMs.', '面向个人 AI 智能体的零代码平台，集成邮件、日历和 CRM。',
   'https://www.lindy.ai', NULL, NULL,
   'AI Agents', 'Agent Platform',
   ARRAY['no-code','personal-agent','workflow-automation','integration'],
   ARRAY['TypeScript','Python','LLM'],
   'freemium', 'https://www.lindy.ai/pricing', 'active',
   'Commercial', 'Series A',
   'Florian Cornu', '2023-04-01', 81, 'medium',
   '{"official_website":true,"media_coverage":true}', 5, 2.0, 8.0, NULL),

  -- ===== AI Productivity (3) =====
  ('grammarly', 'Grammarly', 'Grammarly', 'Grammarly',
   'AI writing assistant with grammar check, tone adjustment, and enterprise governance.', 'AI 写作助手，提供语法检查、语气调整和企业治理。',
   'https://www.grammarly.com', NULL, NULL,
   'AI Productivity', 'Writing Assistant',
   ARRAY['writing-assistant','grammar','enterprise','tone'],
   ARRAY['Python','TypeScript','LLM'],
   'freemium', 'https://www.grammarly.com/plans', 'active',
   'Commercial', 'Public-pending (announced 2025)',
   'Max Lytvyn, Alex Shevchenko', '2009-07-01', 95, 'high',
   '{"official_website":true,"media_coverage":true}', 11, 0.8, 3.2, NULL),

  ('otter-ai', 'Otter.ai', 'Otter.ai', 'Otter.ai',
   'AI meeting assistant that transcribes, summarizes, and identifies action items in real time.', 'AI 会议助手，实时转录、摘要并识别行动项。',
   'https://otter.ai', NULL, NULL,
   'AI Productivity', 'Meeting Assistant',
   ARRAY['meeting-transcription','summary','action-items','real-time'],
   ARRAY['Python','ASR','LLM'],
   'freemium', 'https://otter.ai/pricing', 'active',
   'Commercial', 'Series C',
   'Sam Liang, Yun Fu', '2018-02-01', 90, 'high',
   '{"official_website":true,"media_coverage":true}', 8, 1.0, 4.0, NULL),

  ('mem-ai', 'Mem', 'Mem', 'Mem',
   'AI-powered self-organizing workspace that auto-tags notes and surfaces them contextually.', 'AI 驱动的自组织工作空间，自动打标签并按上下文调出笔记。',
   'https://mem.ai', NULL, NULL,
   'AI Productivity', 'Knowledge Management',
   ARRAY['notes','self-organizing','auto-tagging','knowledge-management'],
   ARRAY['TypeScript','Python','LLM'],
   'freemium', 'https://mem.ai/pricing', 'active',
   'Commercial', 'Series B',
   'Dennis Xu', '2019-09-01', 80, 'medium',
   '{"official_website":true,"media_coverage":true}', 5, 1.5, 6.0, NULL),

  -- ===== AI Audio (3) =====
  ('playht', 'PlayHT', 'PlayHT', 'PlayHT',
   'AI voice generation platform with 600+ voices in 140 languages, including voice cloning.', 'AI 语音生成平台，提供 140 多种语言的 600+ 语音，支持声音克隆。',
   'https://play.ht', NULL, NULL,
   'AI Audio', 'Voice Synthesis',
   ARRAY['voice-synthesis','voice-cloning','multilingual','tts'],
   ARRAY['Python','PyTorch'],
   'freemium', 'https://play.ht/pricing', 'active',
   'Commercial', 'Series A',
   'Mahmoud Felfel', '2016-12-01', 84, 'high',
   '{"official_website":true,"media_coverage":true}', 6, 1.2, 5.0, NULL),

  ('resemble-ai', 'Resemble AI', 'Resemble AI', 'Resemble AI',
   'Enterprise voice AI platform offering realistic voice cloning, real-time TTS, and detection.', '企业级语音 AI 平台，提供逼真的声音克隆、实时 TTS 与检测能力。',
   'https://www.resemble.ai', NULL, NULL,
   'AI Audio', 'Voice Cloning',
   ARRAY['voice-cloning','enterprise','real-time','detection'],
   ARRAY['Python','PyTorch'],
   'paid', 'https://www.resemble.ai/pricing', 'active',
   'Commercial', 'Series A',
   'Zohaib Ahmed', '2019-01-01', 82, 'medium',
   '{"official_website":true,"media_coverage":true}', 5, 0.7, 2.8, NULL),

  ('aiva', 'AIVA', 'AIVA', 'AIVA',
   'AI music composition assistant that creates emotional soundtracks in various styles.', 'AI 音乐创作助手，可按多种风格生成富有情感的原声音乐。',
   'https://www.aiva.ai', NULL, NULL,
   'AI Audio', 'Music Generation',
   ARRAY['music-generation','composition','soundtrack','emotional'],
   ARRAY['Python','PyTorch'],
   'freemium', 'https://www.aiva.ai/pricing', 'active',
   'Commercial', 'Series A',
   'Denis Sureau, Pierre Barreau', '2016-08-01', 79, 'medium',
   '{"official_website":true,"media_coverage":true}', 4, 0.5, 2.0, NULL),

  -- ===== AI Video (3) =====
  ('luma-dream-machine', 'Luma Dream Machine', 'Luma Dream Machine', 'Luma Dream Machine',
   'Luma AI''s text-to-video model generating realistic 5-second videos from text or images.', 'Luma AI 的文生视频模型，可根据文本或图像生成 5 秒写实视频。',
   'https://lumalabs.ai/dream-machine', NULL, NULL,
   'AI Video', 'Video Generation',
   ARRAY['text-to-video','image-to-video','luma','3d-aware'],
   ARRAY['Python','PyTorch','Diffusion'],
   'freemium', 'https://lumalabs.ai/pricing', 'active',
   'Commercial', 'Series B',
   'Amit Jain', '2024-06-12', 90, 'high',
   '{"official_website":true,"media_coverage":true}', 9, 2.5, 10, NULL),

  ('synthesia', 'Synthesia', 'Synthesia', 'Synthesia',
   'Enterprise video generation platform with AI avatars in 140+ languages.', '企业级视频生成平台，提供 140 多种语言的 AI 数字人。',
   'https://www.synthesia.io', NULL, NULL,
   'AI Video', 'Avatar Video',
   ARRAY['avatar-video','enterprise','multilingual','corporate-training'],
   ARRAY['Python','PyTorch'],
   'paid', 'https://www.synthesia.io/pricing', 'active',
   'Commercial', 'Series D ($2.1B valuation)',
   'Victor Riparbelli', '2017-11-01', 91, 'high',
   '{"official_website":true,"media_coverage":true}', 8, 1.0, 4.0, NULL),

  ('heygen', 'HeyGen', 'HeyGen', 'HeyGen',
   'AI video generation platform for creating avatar-led videos with multilingual translation.', 'AI 视频生成平台，可制作带数字人和多语言翻译的视频。',
   'https://www.heygen.com', NULL, NULL,
   'AI Video', 'Avatar Video',
   ARRAY['avatar-video','translation','multilingual','marketing'],
   ARRAY['Python','PyTorch'],
   'freemium', 'https://www.heygen.com/pricing', 'active',
   'Commercial', 'Series C ($500M+ valuation)',
   'Joshua Xu, Wayne Liang', '2020-12-01', 89, 'high',
   '{"official_website":true,"media_coverage":true}', 7, 1.5, 6.0, NULL),

  -- ===== AI Infra (3) =====
  ('huggingface', 'Hugging Face', 'Hugging Face', 'Hugging Face',
   'The AI community platform for models, datasets, and Spaces — the GitHub of machine learning.', '面向模型、数据集和 Spaces 的 AI 社区平台，被誉为机器学习的 GitHub。',
   'https://huggingface.co', 'https://github.com/huggingface', NULL,
   'AI Infra', 'Model Hub',
   ARRAY['model-hub','datasets','open-source','community'],
   ARRAY['Python','Rust','Transformers','PyTorch'],
   'freemium', 'https://huggingface.co/pricing', 'active',
   'Commercial + Open Source', 'Series D ($4.5B valuation)',
   'Clément Delangue, Thomas Wolf', '2016-11-01', 96, 'high',
   '{"official_website":true,"github":true,"media_coverage":true}', 12, 1.2, 5.0, 13000),

  ('replicate', 'Replicate', 'Replicate', 'Replicate',
   'Cloud API for running open-source ML models via a single HTTP call, with Cog for packaging.', '通过单一 HTTP 调用运行开源 ML 模型的云 API，搭配 Cog 进行打包。',
   'https://replicate.com', 'https://github.com/replicate', NULL,
   'AI Infra', 'Inference',
   ARRAY['cloud-inference','open-source-models','cog','api'],
   ARRAY['Python','Cog','Docker'],
   'paid', 'https://replicate.com/pricing', 'active',
   'Commercial', 'Series B',
   'Ben Firshman, Andreas Jansson', '2019-10-01', 87, 'high',
   '{"official_website":true,"github":true,"media_coverage":true}', 7, 1.5, 6.0, 2900),

  ('anyscale', 'Anyscale', 'Anyscale', 'Anyscale',
   'Anyscale is the company behind Ray — distributed compute platform for scaling AI workloads.', 'Anyscale 是 Ray 的背后公司，提供用于扩展 AI 工作负载的分布式计算平台。',
   'https://www.anyscale.com', 'https://github.com/ray-project/ray', NULL,
   'AI Infra', 'Distributed Compute',
   ARRAY['ray','distributed-compute','scaling','ml-platform'],
   ARRAY['Python','C++','Ray'],
   'paid', 'https://www.anyscale.com/pricing', 'active',
   'Commercial', 'Series C',
   'Robert Nishihara, Ion Stoica, Philipp Moritz', '2019-12-01', 86, 'high',
   '{"official_website":true,"github":true,"media_coverage":true}', 7, 0.8, 3.2, 33000),

  -- ===== AI Search (3) =====
  ('brave-search', 'Brave Search', 'Brave Search', 'Brave Search',
   'Privacy-focused independent search engine with an AI-powered summarization layer.', '注重隐私的独立搜索引擎，集成 AI 摘要能力。',
   'https://search.brave.com', NULL, NULL,
   'AI Search', 'Search Engine',
   ARRAY['privacy','search-engine','summarization','independent-index'],
   ARRAY['Rust','Python','LLM'],
   'freemium', 'https://brave.com/search/api/', 'active',
   'Commercial', 'Internal (Brave)',
   'Brendan Eich', '2021-06-22', 86, 'high',
   '{"official_website":true,"media_coverage":true}', 6, 0.8, 3.2, NULL),

  ('andi-search', 'Andi', 'Andi', 'Andi',
   'AI-powered conversational search engine that delivers answers rather than link lists.', 'AI 对话式搜索引擎，直接给出答案而非链接列表。',
   'https://andisearch.com', NULL, NULL,
   'AI Search', 'Answer Engine',
   ARRAY['conversational-search','answer-engine','privacy'],
   ARRAY['Python','LLM'],
   'free', NULL, 'active',
   'Commercial', 'Seed',
   'Angela Hoover, Jed White', '2022-01-01', 78, 'medium',
   '{"official_website":true,"media_coverage":true}', 4, 0.5, 2.0, NULL),

  ('komo', 'Komo AI', 'Komo AI', 'Komo AI',
   'AI search engine focused on generative answers with citations and ad-free experience.', 'AI 搜索引擎，专注生成式答案与引用，无广告体验。',
   'https://komo.ai', NULL, NULL,
   'AI Search', 'Answer Engine',
   ARRAY['generative-search','citations','ad-free'],
   ARRAY['Python','LLM'],
   'free', NULL, 'active',
   'Commercial', 'Seed',
   'Jeffrey Zhu', '2023-04-01', 76, 'medium',
   '{"official_website":true,"media_coverage":true}', 3, 0.3, 1.5, NULL),

  -- ===== AI Education (4) =====
  ('khanmigo', 'Khanmigo', 'Khanmigo', 'Khanmigo',
   'Khan Academy''s AI tutor powered by GPT-4, providing Socratic one-on-one learning.', '可汗学院基于 GPT-4 的 AI 导师，采用苏格拉底式一对一辅导。',
   'https://www.khanmigo.ai', NULL, NULL,
   'AI Education', 'AI Tutor',
   ARRAY['ai-tutor','socratic','education','khan-academy'],
   ARRAY['Python','GPT-4'],
   'freemium', NULL, 'active',
   'Commercial + Non-profit', 'Internal (Khan Academy)',
   'Sal Khan', '2023-03-14', 88, 'high',
   '{"official_website":true,"media_coverage":true}', 7, 1.5, 6.0, NULL),

  ('duolingo-max', 'Duolingo Max', 'Duolingo Max', 'Duolingo Max',
   'Duolingo''s AI-powered subscription tier featuring Explain My Answer and Roleplay features.', 'Duolingo 的 AI 订阅档位，提供「解释我的答案」与「角色扮演」功能。',
   'https://www.duolingo.com', NULL, NULL,
   'AI Education', 'Language Learning',
   ARRAY['language-learning','roleplay','gamified','subscription'],
   ARRAY['Python','GPT-4'],
   'paid', 'https://www.duolingo.com/super', 'active',
   'Commercial', 'Public (DUOL)',
   'Luis von Ahn', '2023-03-15', 89, 'high',
   '{"official_website":true,"media_coverage":true}', 7, 1.0, 4.0, NULL),

  ('speak-app', 'Speak', 'Speak', 'Speak',
   'AI-powered English speaking tutor with real-time feedback on pronunciation and fluency.', 'AI 英语口语导师，对发音与流利度进行实时反馈。',
   'https://www.speak.com', NULL, NULL,
   'AI Education', 'Language Learning',
   ARRAY['speaking-practice','pronunciation','english-tutor','ai-feedback'],
   ARRAY['Python','ASR','LLM'],
   'freemium', 'https://www.speak.com/pricing', 'active',
   'Commercial', 'Series B ($500M+ valuation)',
   'Connor Zwick, Andrew Hsu', '2020-01-01', 86, 'high',
   '{"official_website":true,"media_coverage":true}', 6, 2.0, 8.0, NULL),

  ('quizlet-qchat', 'Quizlet Q-Chat', 'Quizlet Q-Chat', 'Quizlet Q-Chat',
   'Quizlet''s AI study companion offering Socratic-style tutoring across study sets.', 'Quizlet 的 AI 学习伙伴，针对学习集提供苏格拉底式辅导。',
   'https://quizlet.com', NULL, NULL,
   'AI Education', 'AI Study Companion',
   ARRAY['study-companion','flashcards','socratic','quizlet'],
   ARRAY['Python','LLM'],
   'freemium', 'https://quizlet.com/subscriptions', 'active',
   'Commercial', 'Acquired (Mahjong)',
   'Andrew Sutherland', '2023-05-24', 84, 'high',
   '{"official_website":true,"media_coverage":true}', 5, 0.5, 2.0, NULL),

  -- ===== AI Customer Service (3) =====
  ('intercom-fin', 'Intercom Fin', 'Intercom Fin', 'Intercom Fin',
   'Intercom''s AI agent for customer support, resolving up to 50% of support volume automatically.', 'Intercom 的 AI 客服智能体，可自动解决多达 50% 的客服咨询。',
   'https://www.intercom.com/fin', NULL, NULL,
   'AI Customer Service', 'Support Agent',
   ARRAY['support-agent','intercom','enterprise','automation'],
   ARRAY['Python','LLM','RAG'],
   'paid', 'https://www.intercom.com/pricing', 'active',
   'Commercial', 'Public (INTER)',
   'Eoghan McCabe', '2023-03-15', 91, 'high',
   '{"official_website":true,"media_coverage":true}', 8, 1.0, 4.0, NULL),

  ('ada-support', 'Ada', 'Ada', 'Ada',
   'AI-powered customer service automation platform used by enterprises like Meta and Verizon.', 'AI 客服自动化平台，服务于 Meta、Verizon 等企业。',
   'https://www.ada.cx', NULL, NULL,
   'AI Customer Service', 'Support Agent',
   ARRAY['support-automation','enterprise','no-code','multilingual'],
   ARRAY['Python','LLM','RAG'],
   'paid', 'https://www.ada.cx/pricing', 'active',
   'Commercial', 'Series C',
   'Mike Murchison, David Hariri', '2016-04-01', 87, 'high',
   '{"official_website":true,"media_coverage":true}', 6, 0.8, 3.2, NULL),

  ('forethought', 'Forethought', 'Forethought', 'Forethought',
   'AI customer support platform with Triage, Assist, and Discover products using Agatha AI.', 'AI 客服平台，提供 Triage、Assist、Discover 三大产品，由 Agatha AI 驱动。',
   'https://www.forethought.ai', NULL, NULL,
   'AI Customer Service', 'Support Agent',
   ARRAY['triage','assist','discover','enterprise'],
   ARRAY['Python','LLM','RAG'],
   'paid', 'https://www.forethought.ai/pricing', 'active',
   'Commercial', 'Series C',
   'Deon Nicholas', '2018-05-01', 83, 'high',
   '{"official_website":true,"media_coverage":true}', 5, 0.6, 2.4, NULL),

  -- ===== AI Healthcare (2) =====
  ('hippocratic-ai', 'Hippocratic AI', 'Hippocratic AI', 'Hippocratic AI',
   'Safety-first LLM for healthcare, focused on nurse-patient conversations and clinical workflows.', '面向医疗的安全优先大语言模型，专注护患对话与临床工作流。',
   'https://www.hippocraticai.com', NULL, NULL,
   'AI Healthcare', 'Clinical Assistant',
   ARRAY['healthcare','safety','nursing','llm'],
   ARRAY['Python','PyTorch','Healthcare-LLM'],
   'paid', NULL, 'active',
   'Commercial', 'Series B ($500M+ valuation)',
   'Munjal Shah', '2023-11-15', 86, 'high',
   '{"official_website":true,"media_coverage":true}', 6, 1.5, 6.0, NULL),

  ('glass-health', 'Glass Health', 'Glass Health', 'Glass Health',
   'AI clinical decision support for physicians — differential diagnosis and treatment plans.', '面向医生的 AI 临床决策支持，提供鉴别诊断与治疗方案。',
   'https://glass.health', NULL, NULL,
   'AI Healthcare', 'Clinical Assistant',
   ARRAY['clinical-decision','differential-diagnosis','physician','treatment'],
   ARRAY['Python','LLM','RAG'],
   'freemium', 'https://glass.health/pricing', 'active',
   'Commercial', 'Series A',
   'Mikhail Volkov, Graham Ramsey', '2021-08-01', 80, 'medium',
   '{"official_website":true,"media_coverage":true}', 4, 0.7, 2.8, NULL),

  -- ===== AI Marketing (3) =====
  ('jasper-ai', 'Jasper', 'Jasper', 'Jasper',
   'Enterprise marketing content platform with brand voice, campaign automation, and Jasper Chat.', '企业级营销内容平台，支持品牌声音、活动自动化和 Jasper Chat。',
   'https://www.jasper.ai', NULL, NULL,
   'AI Marketing', 'Content Generation',
   ARRAY['marketing-content','brand-voice','campaign','enterprise'],
   ARRAY['Python','LLM'],
   'paid', 'https://www.jasper.ai/pricing', 'active',
   'Commercial', 'Series A ($1.5B valuation)',
   'Dave Rogenmoser', '2021-01-01', 89, 'high',
   '{"official_website":true,"media_coverage":true}', 7, 0.6, 2.4, NULL),

  ('copy-ai', 'Copy.ai', 'Copy.ai', 'Copy.ai',
   'AI copywriting platform for marketing, sales, and operations teams.', '面向营销、销售和运营团队的 AI 文案平台。',
   'https://www.copy.ai', NULL, NULL,
   'AI Marketing', 'Copywriting',
   ARRAY['copywriting','marketing','sales','workflows'],
   ARRAY['Python','LLM'],
   'freemium', 'https://www.copy.ai/pricing', 'active',
   'Commercial', 'Series A',
   'Paul Yacoubian', '2020-10-01', 84, 'high',
   '{"official_website":true,"media_coverage":true}', 5, 0.5, 2.0, NULL),

  ('mutiny', 'Mutiny', 'Mutiny', 'Mutiny',
   'AI personalization platform that turns visitors into customers with no-code website personalization.', 'AI 个性化平台，通过零代码网站个性化将访客转化为客户。',
   'https://www.mutiny.com', NULL, NULL,
   'AI Marketing', 'Personalization',
   ARRAY['personalization','no-code','b2b','conversion'],
   ARRAY['Python','JavaScript','LLM'],
   'paid', 'https://www.mutiny.com/pricing', 'active',
   'Commercial', 'Series B',
   'Jaleh Rezaei, Nikhil Mathew', '2018-08-01', 80, 'medium',
   '{"official_website":true,"media_coverage":true}', 4, 0.6, 2.4, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  name_zh = EXCLUDED.name_zh,
  description_en = EXCLUDED.description_en,
  description_zh = EXCLUDED.description_zh,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  tags = EXCLUDED.tags,
  confidence_score = EXCLUDED.confidence_score,
  confidence_level = EXCLUDED.confidence_level,
  last_seen = NOW();

-- 验证
DO $$
DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM products
  WHERE slug IN (
    'hunyuan','glm-4','doubao','baichuan',
    'adobe-firefly','leonardo-ai','playground-ai',
    'replit','cody','tabnine',
    'autogpt','manus','lindy',
    'grammarly','otter-ai','mem-ai',
    'playht','resemble-ai','aiva',
    'luma-dream-machine','synthesia','heygen',
    'huggingface','replicate','anyscale',
    'brave-search','andi-search','komo',
    'khanmigo','duolingo-max','speak-app','quizlet-qchat',
    'intercom-fin','ada-support','forethought',
    'hippocratic-ai','glass-health',
    'jasper-ai','copy-ai','mutiny'
  );
  RAISE NOTICE 'seed-phase-e-products-40: % products inserted/updated (expected 40)', v_count;
END $$;

-- ANALYZE
ANALYZE products;
