/**
 * Core type definitions for the AI Radar Crawler Service.
 *
 * Defines the product data model, data source interfaces,
 * and configuration types used throughout the crawler pipeline.
 */

/**
 * Represents an AI product discovered by any data source.
 * This is the canonical shape written to Supabase.
 */
export interface CrawledProduct {
  /** Product name (primary identifier) */
  name: string;
  /** URL-safe slug derived from name (auto-generated by enrichment) */
  slug?: string;
  /** English name variant, if known */
  name_en?: string;
  /** Chinese name variant, if known */
  name_zh?: string;
  /** Short description of the product */
  description: string;
  /** Official website URL */
  website_url: string;
  /** GitHub repository URL, if applicable */
  github_url?: string;
  /** Tags / topics associated with the product */
  tags: string[];
  /** High-level category (e.g. "LLM", "Image Generation", "Dev Tools") */
  category: string;
  /** Content type: 'product' for tools/apps, 'news' for industry news */
  content_type?: 'product' | 'news';
  /** Which data source discovered this product */
  source: 'producthunt' | 'github' | 'hackernews' | 'rss' | 'aihot' | 'arxiv' | 'devto' | 'lobsters' | 'npm' | 'reddit' | 'ossinsight' | 'huggingface' | 'telegram' | 'twitter' | 'bluesky';
  /** Original URL where the product was found */
  source_url: string;
  /** ISO timestamp of when this record was crawled */
  crawled_at: string;
  /** GitHub star count, if applicable */
  github_stars?: number;
  /** Pricing model of the product */
  pricing_model?: 'free' | 'freemium' | 'paid' | 'open_source';
}

/**
 * Confidence score attached to a crawled product.
 * - base: 20 (minimum)
 * - max: 100
 */
export interface ScoredProduct extends CrawledProduct {
  /** Confidence score (0-100) */
  confidence_score: number;
  /** Array of source names that mentioned this product */
  source_mentions: string[];
}

/**
 * Generic interface that every data source must implement.
 */
export interface DataSource {
  /** Human-readable name of this source */
  readonly name: string;

  /**
   * Fetch new products from this source.
   * @returns Array of crawled products (may be empty on error)
   */
  fetch(): Promise<CrawledProduct[]>;
}

/**
 * Supabase table row shape for the products table.
 * Matches the schema in 001_initial_schema.sql + 002_add_crawled_columns.sql.
 */
export interface ProductRow {
  id?: string; // UUID
  slug: string;
  name: string;
  name_en?: string;
  name_zh?: string;
  description?: string;
  description_en?: string;
  description_zh?: string;
  website_url?: string;
  github_url?: string;
  logo_url?: string;
  category?: string;
  subcategory?: string;
  content_type?: string; // 'product' | 'news'
  tags?: string[];
  tech_stack?: string[];
  pricing_model?: string;
  pricing_url?: string;
  availability_status?: string;
  commercialization_status?: string;
  funding_stage?: string;
  founder_info?: string;
  launch_date?: string;
  last_seen?: string;
  confidence_score?: number;
  confidence_level?: string;
  validation_signals?: Record<string, unknown>;
  source_count?: number;
  weekly_growth_rate?: number;
  monthly_growth_rate?: number;
  github_stars?: number;
  // Crawler provenance columns (migration 002)
  source?: string;
  source_url?: string;
  source_mentions?: string[];
  crawled_at?: string;
  created_at?: string;
  updated_at?: string;
}
